export type InterfaceLanguage = "ja" | "en" | "ru" | "fr" | "es";

type Gloss = Record<InterfaceLanguage, string>;
const gloss = (ja:string,en:string,ru:string,fr:string,es:string):Gloss => ({ja,en,ru,fr,es});

// These are short learning cues for common graphic components. They are not
// claims about the complete historical etymology of the kanji that contain them.
export const COMPONENT_MEANINGS:Record<string,Gloss> = {
  "一":gloss("一・横線","one / horizontal line","один / горизонтальная черта","un / trait horizontal","uno / trazo horizontal"),
  "丨":gloss("縦線","vertical line","вертикальная черта","trait vertical","trazo vertical"),
  "丶":gloss("点","dot","точка","point","punto"), "丿":gloss("払い・斜線","sweeping stroke","откидная черта","trait oblique","trazo inclinado"),
  "二":gloss("二つ","two","два","deux","dos"), "亠":gloss("ふた・上部","lid / top","крышка / верх","couvercle / haut","tapa / parte superior"),
  "人":gloss("人","person","человек","personne","persona"), "入":gloss("入る","enter","входить","entrer","entrar"),
  "八":gloss("八・分かれる","eight / divide","восемь / разделение","huit / se séparer","ocho / dividir"),
  "冂":gloss("外枠・境界","outer frame / boundary","внешняя рамка / граница","cadre extérieur / limite","marco exterior / límite"),
  "冖":gloss("覆い・屋根","cover / roof","покров / крыша","couverture / toit","cubierta / techo"),
  "冫":gloss("氷・冷たさ","ice / cold","лёд / холод","glace / froid","hielo / frío"),
  "刀":gloss("刀・切る","blade / cut","клинок / резать","lame / couper","hoja / cortar"),
  "力":gloss("力","strength","сила","force","fuerza"), "勹":gloss("包む","wrap / enclose","оборачивать","envelopper","envolver"),
  "匕":gloss("さじ・変化の形","spoon / change shape","ложка / форма изменения","cuillère / forme de changement","cuchara / forma de cambio"),
  "匚":gloss("箱・囲い","box / enclosure","ящик / ограда","boîte / enceinte","caja / recinto"),
  "十":gloss("十・交差","ten / cross","десять / пересечение","dix / croix","diez / cruz"),
  "卜":gloss("占う","divination","гадание","divination","adivinación"), "卩":gloss("ひざまずく人・節","kneeling person / seal","коленопреклонённый / печать","personne agenouillée / sceau","persona arrodillada / sello"),
  "厂":gloss("崖","cliff","утёс","falaise","acantilado"), "厶":gloss("私・曲がった形","private / bent shape","частное / изогнутая форма","privé / forme courbe","privado / forma curva"),
  "又":gloss("右手・手の動き","right hand / action","правая рука / действие","main droite / action","mano derecha / acción"),
  "口":gloss("口・開口部","mouth / opening","рот / отверстие","bouche / ouverture","boca / abertura"),
  "囗":gloss("囲い・範囲","enclosure / area","ограда / область","enceinte / zone","recinto / área"),
  "土":gloss("土・地面","earth / ground","земля / почва","terre / sol","tierra / suelo"),
  "士":gloss("士・人","scholar / person","учёный / человек","lettré / personne","erudito / persona"),
  "夕":gloss("夕方","evening","вечер","soir","tarde"), "大":gloss("大きい・人の形","large / person shape","большой / фигура человека","grand / forme humaine","grande / figura humana"),
  "女":gloss("女性","woman","женщина","femme","mujer"), "子":gloss("子ども","child","ребёнок","enfant","niño"),
  "宀":gloss("屋根・家","roof / house","крыша / дом","toit / maison","techo / casa"),
  "寸":gloss("手・わずかな長さ","hand / small measure","рука / малая мера","main / petite mesure","mano / medida pequeña"),
  "小":gloss("小さい","small","маленький","petit","pequeño"), "尸":gloss("体・垂れた覆い","body / hanging cover","тело / свисающий покров","corps / couverture pendante","cuerpo / cubierta colgante"),
  "山":gloss("山","mountain","гора","montagne","montaña"), "巛":gloss("川・流れ","river / stream","река / поток","rivière / courant","río / corriente"),
  "工":gloss("工作・道具","work / tool","работа / инструмент","travail / outil","trabajo / herramienta"),
  "己":gloss("自分・曲がった形","self / bent shape","сам / изогнутая форма","soi / forme courbe","uno mismo / forma curva"),
  "巾":gloss("布","cloth","ткань","tissu","tela"), "干":gloss("干す・盾の形","dry / shield shape","сушить / форма щита","sécher / forme de bouclier","secar / forma de escudo"),
  "广":gloss("建物・屋根","building / shelter","здание / навес","bâtiment / abri","edificio / refugio"),
  "廾":gloss("両手","two hands","две руки","deux mains","dos manos"), "弓":gloss("弓","bow","лук","arc","arco"),
  "彡":gloss("毛・模様","hair / pattern","волосы / узор","poils / motif","pelo / patrón"), "彳":gloss("歩く・道","step / road","шаг / дорога","pas / chemin","paso / camino"),
  "心":gloss("心・感情","heart / feeling","сердце / чувство","cœur / sentiment","corazón / emoción"),
  "戈":gloss("ほこ・武器","halberd / weapon","алебарда / оружие","hallebarde / arme","alabarda / arma"),
  "戸":gloss("戸・扉","door","дверь","porte","puerta"), "手":gloss("手・動作","hand / action","рука / действие","main / action","mano / acción"),
  "攴":gloss("打つ・動作","strike / action","удар / действие","frapper / action","golpear / acción"),
  "斤":gloss("おの・切る","axe / cut","топор / рубить","hache / couper","hacha / cortar"),
  "方":gloss("方向・四角","direction / square","направление / квадрат","direction / carré","dirección / cuadrado"),
  "日":gloss("太陽・日","sun / day","солнце / день","soleil / jour","sol / día"), "月":gloss("月・月日","moon / month","луна / месяц","lune / mois","luna / mes"),
  "木":gloss("木・樹木","tree / wood","дерево / древесина","arbre / bois","árbol / madera"),
  "欠":gloss("口を開く・不足","open mouth / lack","открытый рот / нехватка","bouche ouverte / manque","boca abierta / falta"),
  "止":gloss("足を止める","stop / foot","остановка / стопа","arrêt / pied","parar / pie"),
  "殳":gloss("手に持つ道具・打つ","hand-held tool / strike","орудие в руке / удар","outil tenu / frapper","herramienta en mano / golpear"),
  "水":gloss("水・流れ","water / flow","вода / поток","eau / courant","agua / corriente"),
  "火":gloss("火・熱","fire / heat","огонь / жар","feu / chaleur","fuego / calor"),
  "爪":gloss("つめ・つかむ手","claw / grasping hand","коготь / хватающая рука","griffe / main qui saisit","garra / mano que agarra"),
  "牛":gloss("牛","cow / ox","корова / бык","vache / bœuf","vaca / buey"), "犬":gloss("犬・動物","dog / animal","собака / животное","chien / animal","perro / animal"),
  "玉":gloss("玉・宝石","jewel / sphere","драгоценность / шар","joyau / sphère","joya / esfera"),
  "田":gloss("田・区画","rice field / plot","рисовое поле / участок","rizière / parcelle","arrozal / parcela"),
  "目":gloss("目・見る","eye / see","глаз / видеть","œil / voir","ojo / ver"),
  "示":gloss("祭壇・示す","altar / show","алтарь / показывать","autel / montrer","altar / mostrar"),
  "石":gloss("石","stone","камень","pierre","piedra"), "禾":gloss("穀物・稲","grain / rice plant","зерно / рис","grain / riz","grano / arroz"),
  "穴":gloss("穴・洞窟","hole / cave","отверстие / пещера","trou / grotte","agujero / cueva"),
  "立":gloss("立つ","stand","стоять","se tenir debout","estar de pie"), "竹":gloss("竹","bamboo","бамбук","bambou","bambú"),
  "米":gloss("米・穀粒","rice / grain","рис / зерно","riz / grain","arroz / grano"),
  "糸":gloss("糸・つながり","thread / connection","нить / связь","fil / lien","hilo / conexión"),
  "网":gloss("網・覆い","net / cover","сеть / покров","filet / couverture","red / cubierta"),
  "羊":gloss("羊","sheep","овца","mouton","oveja"), "肉":gloss("肉・体","flesh / body","плоть / тело","chair / corps","carne / cuerpo"),
  "艸":gloss("草・植物","grass / plant","трава / растение","herbe / plante","hierba / planta"),
  "虫":gloss("虫・小動物","insect / small creature","насекомое / мелкое существо","insecte / petite créature","insecto / criatura pequeña"),
  "衣":gloss("衣服","clothing","одежда","vêtement","ropa"), "言":gloss("言葉・話す","words / speech","слова / речь","paroles / langage","palabras / habla"),
  "貝":gloss("貝・財貨","shell / wealth","раковина / богатство","coquillage / richesse","concha / riqueza"),
  "足":gloss("足・歩く","foot / walk","нога / ходить","pied / marcher","pie / caminar"),
  "車":gloss("車・乗り物","vehicle / wheel","повозка / колесо","véhicule / roue","vehículo / rueda"),
  "辶":gloss("道・進む","road / movement","дорога / движение","chemin / mouvement","camino / movimiento"),
  "邑":gloss("町・場所","village / place","город / место","ville / lieu","pueblo / lugar"),
  "酉":gloss("酒つぼ・酒","wine jar / alcohol","сосуд для вина / алкоголь","jarre à vin / alcool","jarra de vino / alcohol"),
  "金":gloss("金属・金","metal / gold","металл / золото","métal / or","metal / oro"),
  "門":gloss("門・出入口","gate / entrance","ворота / вход","porte / entrée","puerta / entrada"),
  "阜":gloss("丘・段差","hill / mound","холм / насыпь","colline / tertre","colina / montículo"),
  "隹":gloss("尾の短い鳥","short-tailed bird","короткохвостая птица","oiseau à queue courte","ave de cola corta"),
  "雨":gloss("雨・天候","rain / weather","дождь / погода","pluie / temps","lluvia / tiempo"),
  "頁":gloss("頭・顔","head / face","голова / лицо","tête / visage","cabeza / rostro"),
  "食":gloss("食べる・食物","eat / food","есть / пища","manger / nourriture","comer / alimento"),
  "馬":gloss("馬","horse","лошадь","cheval","caballo"),
  "つ":gloss("点のまとまり・形の要素","cluster of strokes / shape cue","группа штрихов / элемент формы","groupe de traits / repère de forme","grupo de trazos / pista de forma"),
};

export const componentMeaning = (component:string, lang:InterfaceLanguage, englishFallback?:string) =>
  COMPONENT_MEANINGS[component]?.[lang] || englishFallback || ({ja:"字形を作る要素",en:"graphic component",ru:"графический компонент",fr:"composant graphique",es:"componente gráfico"} as const)[lang];
