"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import schoolKanjiData from "./data/school-kanji.json";
import SourceNotice from "./source-notice";

type Status = "learning" | "known" | "review" | "stable";
type ReadingSource = "manual"|"saved"|"annotation"|"builtin"|"candidate";
type Entry = { key:string; reading:string; meaning?:string; status:Status; learnedAt:string; lastChecked:string; checks:number; forgot:number; nextReview:string; example:string; streak:number; readingSource?:ReadingSource };
type Book = { id:string; title:string; body:string; createdAt:string; lastRead:string; deletedAt?:string };
type Retention = "7"|"30"|"90"|"never";
type Tab = "home"|"input"|"reading"|"notebook"|"review"|"library"|"history"|"settings";
type KanjiInfo = { literal:string; grade:number; onyomi:string[]; kunyomi:string[]; meanings:string[] };
type ParsedUnit = { text:string; reading?:string; meaning?:string; source?:ReadingSource };

// KANJIDIC由来の常用漢字データから、小学校6学年と中学校相当（grade 8）を採用。
// 文脈を確定できない単漢字には候補だけを出し、AI注釈・熟語辞書・手動修正を優先する。
const SCHOOL_KANJI:Record<string,KanjiInfo> = Object.fromEntries(
  (schoolKanjiData.characters as KanjiInfo[]).map(k=>[k.literal,k])
);
const kataToHira=(s:string)=>s.replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
const cleanReading=(s:string)=>kataToHira(s.replace(/[.\-]/g,""));
const readingCandidates=(k?:KanjiInfo)=>k?[...new Set([...k.onyomi,...k.kunyomi].map(cleanReading).filter(Boolean))]:[];

const SAMPLE = "[今日|きょう|today]は[学校|がっこう|school]の[図書館|としょかん|library]で[日本|にほん|Japan]の[歴史|れきし|history]について[勉強|べんきょう|studied]しました。[最初|さいしょ|at first]は[難しい|むずかしい|difficult][漢字|かんじ|kanji]が[多い|おおい|many]と[思いました|おもいました|thought]が、[少し|すこし|little by little]ずつ[読める|よめる|became able to read]ようになりました。";
const DICT:Record<string,string> = {"図書館":"としょかん","勉強":"べんきょう","難しい":"むずかしい","読める":"よめる","学校":"がっこう","日本":"にほん","歴史":"れきし","最初":"さいしょ","漢字":"かんじ","今日":"きょう","多い":"おおい","少し":"すこし","文章":"ぶんしょう","読む":"よむ","覚える":"おぼえる","毎日":"まいにち","言葉":"ことば","学習":"がくしゅう"};
const BUILTIN_WORDS = Object.keys(DICT).sort((a,b)=>b.length-a.length);
const NAV:{id:Tab;label:string;icon:string}[] = [
  {id:"home",label:"ホーム",icon:"⌂"},{id:"input",label:"文章入力",icon:"＋"},{id:"reading",label:"リーディング",icon:"▤"},{id:"notebook",label:"漢字帳",icon:"字"},{id:"review",label:"復習",icon:"↻"},{id:"library",label:"ライブラリ",icon:"▣"},{id:"history",label:"学習履歴",icon:"⌁"},{id:"settings",label:"設定",icon:"⚙"}
];
type Lang = "ja"|"en"|"ru"|"fr"|"es";
const LANGS:{id:Lang;label:string}[]=[{id:"ja",label:"日本語"},{id:"en",label:"English"},{id:"ru",label:"Русский"},{id:"fr",label:"Français"},{id:"es",label:"Español"}];
const TX:Record<string,string[]>={
"漢字リーディング":["Kanji Reading","Чтение кандзи","Lecture des kanji","Lectura de kanji"],"今日も一歩ずつ":["One step today","Ещё один шаг","Un pas aujourd’hui","Un paso hoy"],
"ホーム":["Home","Главная","Accueil","Inicio"],"文章入力":["Add text","Ввод текста","Saisir un texte","Introducir texto"],"リーディング":["Reading","Чтение","Lecture","Lectura"],"漢字帳":["Kanji notebook","Словарь кандзи","Carnet de kanji","Cuaderno de kanji"],"復習":["Review","Повторение","Révision","Repaso"],"ライブラリ":["Library","Библиотека","Bibliothèque","Biblioteca"],"学習履歴":["Progress","Прогресс","Progression","Progreso"],"設定":["Settings","Настройки","Réglages","Ajustes"],
"おはようございます":["Welcome back","С возвращением","Bienvenue","Bienvenido"],"今日も、ひとつずつ。":["One word at a time.","По одному слову за раз.","Un mot à la fois.","Una palabra a la vez."],"読むほどに、ふりがなが静かに減っていきます。":["As you learn, furigana quietly fades away.","По мере обучения фуригана постепенно исчезает.","À mesure que vous apprenez, les furigana disparaissent.","A medida que aprendes, el furigana desaparece."],"文章を読む":["Read a text","Читать текст","Lire un texte","Leer un texto"],
"今日の復習":["Reviews today","На повторение","Révisions du jour","Repasos de hoy"],"復習を始める →":["Start review →","Начать →","Commencer →","Empezar →"],"覚えた語":["Words learned","Выучено","Mots appris","Palabras aprendidas"],"あなたの読める言葉":["Words you can read","Слова, которые вы читаете","Les mots que vous lisez","Palabras que puedes leer"],"学習中":["Learning","Изучается","En cours","Aprendiendo"],"焦らず育てましょう":["Grow at your pace","Учитесь в своём темпе","À votre rythme","A tu ritmo"],
"最近読んだ文章":["Recently read","Недавние тексты","Lectures récentes","Lecturas recientes"],"すべて見る":["View all","Показать все","Tout voir","Ver todo"],"はじめての方へ":["Getting started","Как начать","Bien démarrer","Primeros pasos"],"3ステップで始められます":["Start in three steps","Три простых шага","Trois étapes simples","Tres pasos sencillos"],"文章を貼り付ける":["Paste a text","Вставьте текст","Collez un texte","Pega un texto"],"ふりがなで読む":["Read with furigana","Читайте с фуриганой","Lisez avec les furigana","Lee con furigana"],"覚えたらタップ":["Tap when learned","Нажмите, когда выучили","Touchez quand c’est acquis","Toca cuando lo aprendas"],
"今日は何を読みますか？":["What will you read today?","Что вы прочитаете сегодня?","Que lirez-vous aujourd’hui ?","¿Qué vas a leer hoy?"],"タイトル":["Title","Заголовок","Titre","Título"],"日本語の文章":["Japanese text","Текст на японском","Texte japonais","Texto japonés"],"サンプルを読み込む":["Load sample","Загрузить пример","Charger l’exemple","Cargar ejemplo"],"入力を削除":["Clear","Очистить","Effacer","Borrar"],"ライブラリに保存":["Save to library","Сохранить","Enregistrer","Guardar"],"ふりがな付き文章に変換 →":["Add furigana →","Добавить фуригану →","Ajouter les furigana →","Añadir furigana →"],
"ふりがな":["Furigana","Фуригана","Furigana","Furigana"],"未学習だけ":["Unlearned only","Только новые","Non appris","Solo no aprendidos"],"すべて表示":["Show all","Показать все","Tout afficher","Mostrar todo"],"復習だけ":["Review only","Только повторение","À réviser","Solo repaso"],"クリックだけ":["On tap only","Только по нажатию","Au toucher","Solo al tocar"],"すべて非表示":["Hide all","Скрыть всё","Tout masquer","Ocultar todo"],"文章を編集":["Edit text","Редактировать","Modifier","Editar"],"保存する":["Save","Сохранить","Enregistrer","Guardar"],
"育てている言葉":["Words you are growing","Ваши изучаемые слова","Les mots que vous cultivez","Palabras que aprendes"],"漢字・読み方で検索":["Search word or reading","Поиск слова или чтения","Rechercher un mot ou une lecture","Buscar palabra o lectura"],"すべての状態":["All statuses","Все статусы","Tous les états","Todos los estados"],"覚えた":["Learned","Выучено","Acquis","Aprendido"],"復習が必要":["Needs review","Нужно повторить","À réviser","Necesita repaso"],"安定":["Stable","Закреплено","Stable","Estable"],"語・読み":["Word / reading","Слово / чтение","Mot / lecture","Palabra / lectura"],"状態":["Status","Статус","État","Estado"],"次回復習":["Next review","Следующее повторение","Prochaine révision","Próximo repaso"],
"復習モード":["Review mode","Режим повторения","Mode révision","Modo repaso"],"読み方を見る":["Show reading","Показать чтение","Voir la lecture","Ver lectura"],"分からなかった":["Didn't know","Не знал","Je ne savais pas","No lo sabía"],"少し迷った":["Hesitated","Сомневался","J’ai hésité","Dudé"],"分かった":["Knew it","Знал","Je savais","Lo sabía"],"すぐ分かった":["Knew instantly","Сразу знал","Immédiatement","Al instante"],"今日の復習は完了です":["Today's review is complete","Повторение завершено","Révision terminée","Repaso completado"],
"読書ライブラリ":["Reading library","Библиотека текстов","Bibliothèque de lecture","Biblioteca de lectura"],"保存した文章":["Saved texts","Сохранённые тексты","Textes enregistrés","Textos guardados"],"＋ 新しい文章":["＋ New text","＋ Новый текст","＋ Nouveau texte","＋ Nuevo texto"],"もう一度読む":["Read again","Читать снова","Relire","Leer de nuevo"],"削除":["Delete","Удалить","Supprimer","Eliminar"],
"積み重ねが見える場所":["See how far you have come","Посмотрите свой прогресс","Visualisez vos progrès","Mira cuánto has avanzado"],"登録した語":["Saved words","Сохранено слов","Mots enregistrés","Palabras guardadas"],"確認した回数":["Reading checks","Проверки чтения","Lectures vérifiées","Lecturas comprobadas"],"よく忘れる語":["Often forgotten","Часто забываются","Souvent oubliés","Olvidadas a menudo"],
"読みやすさとデータ":["Reading and data","Чтение и данные","Lecture et données","Lectura y datos"],"本文の文字サイズ":["Text size","Размер текста","Taille du texte","Tamaño del texto"],"行間":["Line spacing","Межстрочный интервал","Interligne","Interlineado"],"ダークテーマ":["Dark theme","Тёмная тема","Thème sombre","Tema oscuro"],"データ管理":["Data management","Управление данными","Gestion des données","Gestión de datos"],"JSONを書き出す":["Export JSON","Экспорт JSON","Exporter JSON","Exportar JSON"],"JSONを読み込む":["Import JSON","Импорт JSON","Importer JSON","Importar JSON"],
"学習する語":["Word to learn","Новое слово","Mot à apprendre","Palabra por aprender"],"読み未登録":["Reading not registered","Чтение не указано","Lecture non renseignée","Lectura no registrada"],"読み方を修正":["Edit reading","Изменить чтение","Modifier la lecture","Editar lectura"],"✓ 覚えた":["✓ Learned","✓ Выучено","✓ Acquis","✓ Aprendido"],"↻ 復習対象に戻す":["↻ Return to review","↻ Вернуть на повторение","↻ Remettre à réviser","↻ Volver a repasar"],"一度だけ読みを表示":["Show once","Показать один раз","Afficher une fois","Mostrar una vez"],"この文章では表示":["Show in this text","Показывать в этом тексте","Afficher dans ce texte","Mostrar en este texto"]};
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const expired=(date:string,days:number)=>Date.now()-new Date(`${date}T00:00:00`).getTime()>=days*86400000;

export default function Home(){
  const [tab,setTab]=useState<Tab>("home"); const [text,setText]=useState(SAMPLE); const [title,setTitle]=useState("図書館での一日");
  const [entries,setEntries]=useState<Record<string,Entry>>({}); const [books,setBooks]=useState<Book[]>([]); const [selected,setSelected]=useState<string|null>(null);
  const [temp,setTemp]=useState<string[]>([]); const [session,setSession]=useState<string[]>([]); const [mode,setMode]=useState("unknown");
  const [fontSize,setFontSize]=useState(25); const [lineHeight,setLineHeight]=useState(2.35); const [dark,setDark]=useState(false); const [vertical,setVertical]=useState(false);
  const [reviewIndex,setReviewIndex]=useState(0); const [showAnswer,setShowAnswer]=useState(false); const [notice,setNotice]=useState(""); const [hydrated,setHydrated]=useState(false); const [lang,setLang]=useState<Lang>("ja"); const [copied,setCopied]=useState(false);
  const [retention,setRetention]=useState<Retention>("30"); const [discardUnsaved,setDiscardUnsaved]=useState(false); const [draftSaved,setDraftSaved]=useState(false); const [textUpdatedAt,setTextUpdatedAt]=useState(today());
  useEffect(()=>{queueMicrotask(()=>{try{const savedEntries=JSON.parse(localStorage.getItem("kanji-reader-entries")||"{}");const savedBooks:Book[]=JSON.parse(localStorage.getItem("kanji-reader-books")||"[]");const s=JSON.parse(localStorage.getItem("kanji-reader-settings")||"{}");const keep:Retention=s.retention||"30";const days=keep==="never"?null:Number(keep);const currentExpired=!!(days&&s.text&&s.textUpdatedAt&&expired(s.textUpdatedAt,days));const bodyExpired=savedBooks.some(b=>!!b.body&&!!days&&expired(b.lastRead,days));setEntries(currentExpired||bodyExpired?Object.fromEntries(Object.entries(savedEntries).map(([k,v])=>[k,{...(v as Entry),example:""}])):savedEntries);setBooks(savedBooks.map(b=>b.body&&days&&expired(b.lastRead,days)?{...b,body:"",deletedAt:today()}:b));if(s.mode)setMode(s.mode);if(s.fontSize)setFontSize(s.fontSize);if(s.lineHeight)setLineHeight(s.lineHeight);if(s.dark)setDark(s.dark);if(s.lang)setLang(s.lang);setRetention(keep);setDiscardUnsaved(!!s.discardUnsaved);if(currentExpired){setText("");setTitle("");setDraftSaved(false)}else{if(s.text!==undefined)setText(s.text);if(s.title)setTitle(s.title);setDraftSaved(!!s.draftSaved)}if(s.textUpdatedAt)setTextUpdatedAt(s.textUpdatedAt)}catch{}setHydrated(true)})},[]);
  useEffect(()=>{if(!hydrated)return;localStorage.setItem("kanji-reader-entries",JSON.stringify(entries));localStorage.setItem("kanji-reader-books",JSON.stringify(books));localStorage.setItem("kanji-reader-settings",JSON.stringify({mode,fontSize,lineHeight,dark,lang,text,title,retention,discardUnsaved,draftSaved,textUpdatedAt}))},[entries,books,mode,fontSize,lineHeight,dark,lang,text,title,retention,discardUnsaved,draftSaved,textUpdatedAt,hydrated]);
  useEffect(()=>{document.documentElement.lang=lang;const idx={en:0,ru:1,fr:2,es:3} as const;const reverse=new Map<string,string>();Object.entries(TX).forEach(([ja,a])=>{reverse.set(ja,ja);a.forEach(x=>reverse.set(x,ja))});const run=()=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(w.nextNode())nodes.push(w.currentNode as Text);nodes.forEach(n=>{if(n.parentElement?.closest(".reading-text,ruby,rt,textarea,input"))return;const raw=n.nodeValue||"",s=raw.trim(),base=reverse.get(s);if(!base)return;const out=lang==="ja"?base:TX[base]?.[idx[lang]]||base;if(out!==s)n.nodeValue=raw.replace(s,out)});document.querySelectorAll<HTMLInputElement>("input[placeholder]").forEach(el=>{const base=reverse.get(el.placeholder)||el.placeholder;el.placeholder=lang==="ja"?base:TX[base]?.[idx[lang]]||base})};run();const ob=new MutationObserver(run);ob.observe(document.body,{childList:true,subtree:true});return()=>ob.disconnect()},[lang,tab,selected,showAnswer]);
  const due=useMemo(()=>Object.values(entries).filter(e=>e.status==="review"||e.nextReview<=today()),[entries]);
  const known=Object.values(entries).filter(e=>e.status==="known"||e.status==="stable").length;
  const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2200)};
  // 個人辞書（これまでに保存・修正した語）を最優先し、その次に内蔵熟語を長い順で照合する。
  // 文脈を判定できない単漢字は、本文上で読みを断定せず「候補あり」としてだけ扱う。
  const personalWords=useMemo(()=>Object.keys(entries).filter(w=>entries[w]?.reading).sort((a,b)=>b.length-a.length),[entries]);
  const parseLegacy=(s:string)=>{const out:ParsedUnit[]=[];let i=0;while(i<s.length){const personal=personalWords.find(x=>s.startsWith(x,i));if(personal){out.push({text:personal,reading:entries[personal].reading,meaning:entries[personal].meaning,source:"saved"});i+=personal.length;continue}const builtin=BUILTIN_WORDS.find(x=>s.startsWith(x,i));if(builtin){out.push({text:builtin,reading:DICT[builtin],source:"builtin"});i+=builtin.length;continue}const c=s[i];out.push(SCHOOL_KANJI[c]?{text:c,source:"candidate"}:{text:c});i++}return out};
  // 推奨形式は「[表記|よみ|意味]」。表記そのものも角括弧内に入るため、
  // 助詞や前の文節を誤ってrubyへ取り込まない。既存データを守るため、
  // 従来の「語[よみ|意味]」と意味を省略した形式も引き続き解析する。
  const parse=(s:string)=>{const out:ParsedUnit[]=[];const pattern=/\[([^|\]\n]+)\|([^|\]\n]+)(?:\|([^\]\n]+))?\]|([々一-龯][々一-龯ぁ-んァ-ヶー]*)\[([^\]|\n]+)(?:\|([^\]\n]+))?\]/g;let cursor=0;for(const match of s.matchAll(pattern)){const start=match.index??0;if(start>cursor)out.push(...parseLegacy(s.slice(cursor,start)));const modern=match[1]!==undefined;out.push({text:(modern?match[1]:match[4]).trim(),reading:(modern?match[2]:match[5]).trim(),meaning:(modern?match[3]:match[6])?.trim(),source:"annotation"});cursor=start+match[0].length}if(cursor<s.length)out.push(...parseLegacy(s.slice(cursor)));return out};
  const parsed=parse(text);
  const annotations=Object.fromEntries(parsed.filter(p=>p.reading).map(p=>[p.text,{reading:p.reading||"",meaning:p.meaning||""}]));
  const readingFor=(word:string)=>entries[word]?.reading||annotations[word]?.reading||DICT[word]||"";
  const sourceFor=(word:string):ReadingSource=>entries[word]?.readingSource||((entries[word]?.reading)?"saved":parsed.find(p=>p.text===word)?.source)||"candidate";
  const sourceLabel=(source:ReadingSource)=>({manual:"手動で修正した読み",saved:"個人辞書に保存済み",annotation:"入力された注釈",builtin:"内蔵熟語辞書",candidate:"漢字辞書の候補（未確定）"} as Record<ReadingSource,string>)[source];
  const visible=(w:string)=>{const e=entries[w];if(temp.includes(w)||session.includes(w))return true;if(mode==="all")return true;if(mode==="none"||mode==="click")return false;if(mode==="review")return e?.status==="review"||!!e&&e.nextReview<=today();return !e||e.status==="learning"||e.status==="review"||e.nextReview<=today()};
  const upsert=(word:string,status:Status)=>{const reading=readingFor(word);if(!reading){toast("先に正しい読み方を選択または入力してください");return}const old=entries[word];setEntries({...entries,[word]:{key:word,reading,meaning:old?.meaning||annotations[word]?.meaning||"",status,learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:(old?.checks||0)+(status==="known"?1:0),forgot:(old?.forgot||0)+(status==="review"?1:0),nextReview:addDays(status==="review"?1:status==="known"?3:7),example:text,streak:status==="known"?(old?.streak||0)+1:0,readingSource:old?.readingSource||sourceFor(word)}});setSelected(null);toast(status==="known"?`「${word}」を覚えた語に登録しました`:`「${word}」を復習に戻しました`)};
  const changeReading=(word:string)=>{const proposed=sourceFor(word)==="candidate"?prompt("個人辞書に登録する単語・熟語を入力してください",word):word;if(proposed===null)return;const target=proposed.trim();if(!target)return;if(!text.includes(target)){toast("現在の本文にある語を入力してください");return}const r=prompt("正しい読み方をひらがなで入力してください",entries[target]?.reading||readingFor(target));if(r!==null&&r.trim()){const old=entries[target];setEntries({...entries,[target]:{key:target,reading:cleanReading(r.trim()),meaning:old?.meaning||annotations[target]?.meaning||"",status:old?.status||"learning",learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:old?.checks||0,forgot:old?.forgot||0,nextReview:old?.nextReview||addDays(1),example:text,streak:old?.streak||0,readingSource:"manual"}});setSelected(null);toast(`「${target}」を個人辞書に保存しました`)}};
  const chooseReading=(word:string,reading:string)=>{const old=entries[word];setEntries({...entries,[word]:{key:word,reading:cleanReading(reading),meaning:old?.meaning||annotations[word]?.meaning||"",status:old?.status||"learning",learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:old?.checks||0,forgot:old?.forgot||0,nextReview:old?.nextReview||addDays(1),example:text,streak:old?.streak||0,readingSource:"manual"}});toast(`「${word}」の読みを個人辞書に保存しました`)};
  const saveBook=()=>{if(!text.trim()){toast("保存する本文がありません");return}const b:Book={id:crypto.randomUUID(),title:title||"無題の文章",body:text,createdAt:today(),lastRead:today()};setBooks([b,...books]);setDraftSaved(true);setTextUpdatedAt(today());toast("読書ライブラリに保存しました")};
  const startReading=()=>{setTextUpdatedAt(today());setTab("reading");setSelected(null)};
  const openBook=(book:Book)=>{if(!book.body){toast("この文章の本文は保存期限により削除されています");return}setBooks(books.map(b=>b.id===book.id?{...b,lastRead:today()}:b));setTitle(book.title);setText(book.body);setTextUpdatedAt(today());setDraftSaved(true);setTab("reading")};
  const navigate=(next:Tab)=>{if(tab==="reading"&&next!=="reading"&&discardUnsaved&&!draftSaved){setText("");setTitle("");setTextUpdatedAt(today());setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])));toast("保存していない本文を破棄しました")}setTab(next);setSelected(null)};
  const updateRetention=(value:Retention)=>{if(value==="never"&&!confirm("著作権の問題はそれぞれの国によって異なります。本文を期限なく保存することについて、ご自身で責任を持ちますか？"))return;setRetention(value);if(value!=="never"){const days=Number(value);const purged=books.some(b=>b.body&&expired(b.lastRead,days));setBooks(books.map(b=>b.body&&expired(b.lastRead,days)?{...b,body:"",deletedAt:today()}:b));if(text&&expired(textUpdatedAt,days)){setText("");setTitle("");setDraftSaved(false)}if(purged)setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])))}toast(value==="never"?"本文を自動削除しない設定にしました":`本文を${value}日後に自動削除します`)};
  const deleteAllBodies=()=>{if(!confirm("保存中の本文をすべて削除しますか？ 学習した語・読み・復習記録は残ります。"))return;setText("");setTitle("");setDraftSaved(false);setTextUpdatedAt(today());setBooks(books.map(b=>({...b,body:"",deletedAt:today()})));setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])));toast("本文だけを削除しました")};
  const copyPrompt=async()=>{const prompt=`Rewrite the Japanese text below for use in a Japanese reading-learning application.

First, silently divide each sentence into natural Japanese bunsetsu (文節). Then identify the exact word or meaningful expression containing kanji inside each bunsetsu. Annotate only that kanji-containing lexical unit. Never attach a preceding particle, auxiliary expression, or unrelated hiragana from the previous part of the sentence to the annotated word.

For every word or expression that contains kanji, use exactly this format:

[Japanese surface text|hiragana reading|short contextual meaning in English]

Example:

[今日|きょう|today]は[学校|がっこう|school]の[図書館|としょかん|library]で[日本|にほん|Japan]の[歴史|れきし|history]について[勉強|べんきょう|studied]しました。

The entire annotated unit, including the original Japanese surface text, must be placed inside the square brackets.

Correct:

[今回|こんかい|this time]の[移民急増|いみんきゅうぞう|sharp increase in immigration]は[犯罪組織|はんざいそしき|criminal organization]

Incorrect:

今回[こんかい|this time]の移民急増[いみんきゅうぞう|sharp increase in immigration]

Follow these rules carefully:

1. Before annotating, silently determine the bunsetsu boundaries and the word boundaries within each bunsetsu.
2. Annotate every word or meaningful expression that contains kanji.
3. Put the exact Japanese surface text, its reading, and its meaning together inside one pair of square brackets. Never place the Japanese surface text outside the brackets.
4. Use the reading required by the actual sentence context.
5. Do not determine readings by mechanically separating individual kanji.
6. Prefer complete words and compounds, such as [今日|きょう|today], [図書館|としょかん|library], and [日本|にほん|Japan].
7. Keep okurigana that belongs to the word inside the Japanese surface field, such as [難しい|むずかしい|difficult] and [読める|よめる|can read]. Do not include following auxiliaries unless they form one meaningful expression that should be learned together.
8. Write readings entirely in hiragana. Do not use romaji or IPA.
9. Give one short English meaning that fits the word in that sentence. Do not list multiple dictionary meanings.
10. Preserve the original wording, word order, punctuation, paragraph breaks, dialogue structure, speaker names, spaces, and numbers.
11. Leave words written only in hiragana or katakana unchanged unless they are an inseparable part of a kanji-containing word.
12. For names and place names, choose the most contextually probable reading and do not omit the annotation.
13. Put punctuation outside the annotation.
14. Do not insert spaces unless they already exist in the original.
15. Do not use Markdown tables, bullet points, code blocks, explanations, notes, headings, introductions, or summaries in the output.
16. Output only the converted Japanese text.
17. Before answering, verify that every annotated unit follows exactly: [Japanese surface text|hiragana reading|short contextual meaning in English]

Japanese text:
`;await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1800)};
  const evaluate=useCallback((score:number)=>{const e=due[reviewIndex];if(!e)return;const days=[1,2,7,14][score-1];setEntries({...entries,[e.key]:{...e,status:score===1?"review":score===4&&e.streak>=3?"stable":"known",checks:e.checks+1,forgot:e.forgot+(score===1?1:0),streak:score===1?0:e.streak+1,lastChecked:today(),nextReview:addDays(days)}});setShowAnswer(false);setReviewIndex(Math.min(reviewIndex+1,due.length-1));toast("次回の復習日を更新しました")},[due,reviewIndex,entries]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(tab!=="review")return;if(e.code==="Space"){e.preventDefault();setShowAnswer(true)}if(showAnswer&&/[1-4]/.test(e.key))evaluate(Number(e.key))};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[tab,showAnswer,evaluate]);
  const readingText=<div className={`reading-text ${vertical?"vertical":""}`} style={{fontSize,lineHeight}}>{parsed.map((p,i)=>p.reading||p.source==="candidate"?<button key={i} className={`word ${entries[p.text]?.status||"new"} ${temp.includes(p.text)?"temporary":""} ${p.source==="candidate"?"dictionary-candidate":""}`} aria-label={p.source==="candidate"?`${p.text}、読み候補を確認`:`${p.text}、読みと学習状態を確認`} onClick={()=>setSelected(p.text)}>{p.reading&&visible(p.text)?<ruby>{p.text}<rt style={{fontSize:`${Math.max(10,fontSize*.48)}px`}}>{readingFor(p.text)}{p.meaning?` · ${p.meaning}`:""}</rt></ruby>:p.text}</button>:p.text)}</div>;
  const current=selected?entries[selected]:null;
  const selectedKanji=selected?[...selected].map(c=>SCHOOL_KANJI[c]).filter((k):k is KanjiInfo=>!!k):[];
  const selectedSource=selected?sourceFor(selected):"candidate";
  return <div className={`app ${dark?"dark":""}`}>
    <header><button className="brand" onClick={()=>setTab("home")} aria-label="ホームへ"><span>読</span><b>漢字リーディング</b></button><div className="header-actions"><label className="language-picker" aria-label="Interface language"><span>文A</span><select value={lang} onChange={e=>setLang(e.target.value as Lang)}>{LANGS.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label><span className="streak">今日も一歩ずつ</span><button className="round" onClick={()=>setDark(!dark)} aria-label="テーマ切替">{dark?"☀":"☾"}</button></div></header>
    <aside aria-label="メインナビゲーション">{NAV.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>navigate(n.id)}><i>{n.icon}</i><span>{n.label}</span>{n.id==="review"&&due.length>0?<em>{due.length}</em>:null}</button>)}</aside>
    <main>
      {tab==="home"&&<><section className="welcome"><div><small>おはようございます</small><h1>今日も、ひとつずつ。</h1><p>読むほどに、ふりがなが静かに減っていきます。</p></div><button className="primary" onClick={()=>navigate("input")}>文章を読む <span>→</span></button></section><section className="stats"><article><span>今日の復習</span><strong>{due.length}<small>語</small></strong><button onClick={()=>navigate("review")}>復習を始める →</button></article><article><span>覚えた語</span><strong>{known}<small>語</small></strong><p>あなたの読める言葉</p></article><article><span>学習中</span><strong>{Object.keys(entries).length-known}<small>語</small></strong><p>焦らず育てましょう</p></article></section><section className="home-grid"><article className="recent"><div className="section-title"><h2>最近読んだ文章</h2><button onClick={()=>navigate("library")}>すべて見る</button></div>{books.length?books.slice(0,3).map(b=><button className="book-row" key={b.id} onClick={()=>openBook(b)} disabled={!b.body}><span>文</span><div><b>{b.title}</b><small>{b.body?`${b.lastRead}に読書`:"本文削除済み"}</small></div><i>{b.body?"→":"—"}</i></button>):<div className="empty"><span>◫</span><p>保存した文章がここに並びます</p><button onClick={()=>navigate("input")}>最初の文章を読む</button></div>}</article><article className="guide"><span>はじめての方へ</span><h2>3ステップで始められます</h2><ol><li><b>1</b><p><strong>文章を貼り付ける</strong><small>読みたい日本語を入力します</small></p></li><li><b>2</b><p><strong>ふりがなで読む</strong><small>分からない語も止まらず読めます</small></p></li><li><b>3</b><p><strong>覚えたらタップ</strong><small>次からふりがなが消えます</small></p></li></ol></article></section></>}
      {tab==="input"&&<section className="panel input-panel"><div className="eyebrow">注釈付き文章入力</div><h1>今日は何を読みますか？</h1><div className="copyright-note">自分で利用できる文章だけを入力してください。著作権に関する法律は国によって異なります。</div><div className="offline-analysis"><div><b>AIなしでも、内蔵辞書と個人辞書で読みを支援します</b><p>登録済みの熟語と、あなたが過去に修正した語を優先して認識します。文脈から確定できない漢字は、誤った読みを本文へ出さず、押したときだけ候補を表示します。</p></div><small>文章を外部へ送信しません。候補を選択または手動修正すると、その端末の個人辞書に保存され、次回から自動的に使われます。</small></div><div className="format-guide"><b>より正確な読みと意味が必要な場合はAI形式を使います</b><code>[勉強|べんきょう|studied]しました</code><p>日本語の語・ひらがなの読み・英語の意味を、すべて角括弧の中に入れます。従来の 学校[がっこう|school] 形式も引き続き読み込めます。</p><button onClick={copyPrompt}>{copied?"✓ コピーしました":"新形式のAI用英語プロンプトをコピー"}</button></div><label>タイトル<input value={title} onChange={e=>{setTitle(e.target.value);setDraftSaved(false);setTextUpdatedAt(today())}} /></label><label>日本語の文章<textarea value={text} onChange={e=>{setText(e.target.value);setDraftSaved(false);setTextUpdatedAt(today())}} rows={12}/></label><div className="parse-count">確定した読み：<b>{parsed.filter(p=>p.reading).length}</b>　未確定の漢字：<b>{parsed.filter(p=>p.source==="candidate").length}</b></div><div className="actions"><button className="ghost" onClick={()=>{setText(SAMPLE);setDraftSaved(false);setTextUpdatedAt(today())}}>サンプルを読み込む</button><button className="ghost" onClick={()=>{setText("");setTitle("");setDraftSaved(false);setTextUpdatedAt(today())}}>入力を削除</button><button className="secondary" onClick={saveBook}>ライブラリに保存</button><button className="primary" onClick={startReading}>読書画面を開く →</button></div></section>}
      {tab==="reading"&&<section className="reader"><div className="reader-top"><div><div className="eyebrow">リーディング</div><h1>{title}</h1></div><div className="reader-tools"><label>ふりがな<select value={mode} onChange={e=>setMode(e.target.value)}><option value="unknown">未学習だけ</option><option value="all">すべて表示</option><option value="review">復習だけ</option><option value="click">クリックだけ</option><option value="none">すべて非表示</option></select></label><button onClick={()=>setFontSize(Math.max(18,fontSize-2))}>A−</button><button onClick={()=>setFontSize(Math.min(42,fontSize+2))}>A＋</button><button onClick={()=>setVertical(!vertical)}>縦/横</button></div></div><div className="paper">{readingText}</div><div className="reading-legend"><span><i className="legend-dot"/>読みが確定している語</span><span><i className="legend-unknown"/>点線は読み候補あり（未確定）</span></div><div className="reader-foot"><button onClick={()=>setTab("input")}>← 文章を編集</button><span>語をタップすると、読み方と学習状態を変更できます</span><div><button onClick={()=>navigate("home")}>読書を終了</button><button onClick={saveBook}>保存する</button></div></div></section>}
      {tab==="notebook"&&<Notebook entries={entries} onSelect={setSelected}/>} 
      {tab==="review"&&<section className="panel review"><div className="eyebrow">復習モード</div><h1>今日の復習</h1>{due.length?<><p>{reviewIndex+1} / {due.length}</p><div className="review-card"><strong>{due[reviewIndex]?.key}</strong>{showAnswer&&<span>{due[reviewIndex]?.reading}</span>}</div>{!showAnswer?<button className="primary" onClick={()=>setShowAnswer(true)}>読み方を見る <kbd>Space</kbd></button>:<div className="ratings">{["分からなかった","少し迷った","分かった","すぐ分かった"].map((x,i)=><button key={x} onClick={()=>evaluate(i+1)}>{x}<kbd>{i+1}</kbd></button>)}</div>}</>:<div className="empty"><span>✓</span><h2>今日の復習は完了です</h2><p>新しい文章を読んで、言葉を育てましょう。</p></div>}</section>}
      {tab==="library"&&<section className="panel"><div className="section-title"><div><div className="eyebrow">読書ライブラリ</div><h1>保存した文章</h1></div><button className="primary" onClick={()=>navigate("input")}>＋ 新しい文章</button></div><div className="retention-summary">本文は最後に読んだ日から {retention==="never"?"削除しない設定です":`${retention}日後に自動削除されます`}。学習記録は残ります。</div><div className="book-grid">{books.map(b=><article key={b.id} className={!b.body?"body-deleted":""}><span>{b.body?"日本語":"本文削除済み"}</span><h3>{b.title}</h3><p>{b.body?`${b.body.slice(0,75)}…`:"本文は保存期限または手動操作により削除されました。"}</p><small>{b.createdAt} 登録</small><div>{b.body&&<button onClick={()=>openBook(b)}>もう一度読む</button>}<button onClick={()=>setBooks(books.filter(x=>x.id!==b.id))}>削除</button></div></article>)}</div>{!books.length&&<div className="empty"><span>▣</span><p>まだ文章が保存されていません</p></div>}</section>}
      {tab==="history"&&<History entries={entries}/>} 
      {tab==="settings"&&<section className="panel settings"><div className="eyebrow">設定</div><h1>読みやすさとデータ</h1><div className="dictionary-summary"><b>内蔵漢字辞書：{Object.keys(SCHOOL_KANJI).length.toLocaleString()}字</b><p>義務教育で扱う常用漢字の音読み・訓読みを収録しています。文脈を確定できない場合、本文には読みを断定表示しません。候補を選択・修正した語は個人辞書としてこのブラウザに保存され、次回から内蔵熟語より先に照合されます。</p><p>個人辞書：{Object.values(entries).filter(e=>e.reading).length.toLocaleString()}語</p></div><div className="setting-row"><div><b>本文の文字サイズ</b><small>{fontSize}px</small></div><input type="range" min="18" max="42" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></div><div className="setting-row"><div><b>行間</b><small>{lineHeight.toFixed(1)}</small></div><input type="range" min="1.7" max="3" step=".1" value={lineHeight} onChange={e=>setLineHeight(+e.target.value)}/></div><div className="setting-row"><div><b>ダークテーマ</b><small>目の負担を抑えます</small></div><button className="toggle" aria-pressed={dark} onClick={()=>setDark(!dark)}><i/></button></div><section className="privacy-settings"><h2>本文の保存と著作権</h2><p>標準では、最後に読んでから30日後に本文だけを削除します。学習した語・読み・復習記録は残ります。</p><label>本文の保存期間<select value={retention} onChange={e=>updateRetention(e.target.value as Retention)}><option value="7">7日</option><option value="30">30日（標準）</option><option value="90">90日</option><option value="never">削除しない</option></select></label>{retention==="never"&&<div className="copyright-warning">著作権の問題はそれぞれの国によって異なります。保存する文章については、ご自身で責任を持って管理してください。</div>}<label className="check-setting"><input type="checkbox" checked={discardUnsaved} onChange={e=>setDiscardUnsaved(e.target.checked)}/><span><b>保存していない文章は読書終了時に破棄する</b><small>漢字帳と復習記録は残ります。</small></span></label><button className="delete-bodies" onClick={deleteAllBodies}>今すぐ本文を削除</button></section><DataTools entries={entries} books={books} setEntries={setEntries} setBooks={setBooks} toast={toast}/></section>}
      {tab==="settings"&&<SourceNotice/>}
    </main>
    {selected&&<div className="modal-back" onMouseDown={()=>setSelected(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="word-dialog-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="閉じる">×</button><small>{current?.status==="known"?"覚えた語":current?.status==="review"?"復習が必要":"学習する語"}</small><h2 id="word-dialog-title">{selected}</h2><div className="reading-answer">{readingFor(selected)||"読みはまだ確定していません"}</div><div className={`reading-source ${selectedSource}`}>{sourceLabel(selectedSource)}{selectedSource==="candidate"&&selectedKanji[0]?`・${readingCandidates(selectedKanji[0]).length}候補`:""}</div>{(current?.meaning||annotations[selected]?.meaning)&&<div className="meaning-answer">{current?.meaning||annotations[selected]?.meaning}</div>}{selectedKanji.length>0&&<div className="kanji-details"><b>{selectedSource==="candidate"?"候補から選ぶ":"内蔵漢字辞書の別候補"}</b>{selectedKanji.map(k=><div className="kanji-row" key={k.literal}><span className="kanji-literal">{k.literal}</span><div className="kanji-readings"><p><small>音読み</small>{k.onyomi.length?k.onyomi.map(r=>selected.length===1?<button key={r} onClick={()=>chooseReading(selected,r)} aria-label={`${selected}の読みを${cleanReading(r)}にする`}>{r}</button>:<span key={r}>{r}</span>):"—"}</p><p><small>訓読み</small>{k.kunyomi.length?k.kunyomi.map(r=>selected.length===1?<button key={r} onClick={()=>chooseReading(selected,r)} aria-label={`${selected}の読みを${cleanReading(r)}にする`}>{r}</button>:<span key={r}>{r}</span>):"—"}</p></div></div>)}<small>ここにある読みは候補です。熟語・送り仮名・文脈に合うものがない場合は、下の「読み方を修正」から正しい読みを入力してください。</small></div>}<button className="edit-reading" onClick={()=>changeReading(selected)}>✎ 読み方を修正</button><div className="modal-actions"><button className="primary" onClick={()=>upsert(selected,"known")}>✓ 覚えた</button><button onClick={()=>upsert(selected,"review")}>↻ 復習対象に戻す</button><button disabled={!readingFor(selected)} onClick={()=>{setTemp([...temp,selected]);setSelected(null);setTimeout(()=>setTemp(v=>v.filter(x=>x!==selected)),5000)}}>一度だけ読みを表示</button><button disabled={!readingFor(selected)} onClick={()=>{setSession([...session,selected]);setSelected(null)}}>この文章では表示</button></div><p>{readingFor(selected)?"一度だけ表示した読みは、5秒後に再び隠れます。":"読みを確定すると、個人辞書として次回の文章でも使われます。"}</p></div></div>}
    {notice&&<div className="toast" role="status">✓ {notice}</div>}
  </div>
}

function DictionaryLookup({onSelect}:{onSelect:(x:string)=>void}){const [query,setQuery]=useState("");const normalized=kataToHira(query.trim());const matches=normalized?Object.values(SCHOOL_KANJI).filter(k=>k.literal.includes(query)||[...k.onyomi,...k.kunyomi].some(r=>cleanReading(r).includes(normalized))).slice(0,24):[];return <section className="dictionary-lookup"><div><b>内蔵漢字辞書</b><small> 義務教育の常用漢字 {Object.keys(SCHOOL_KANJI).length.toLocaleString()}字</small></div><input aria-label="内蔵漢字辞書を検索" placeholder="漢字・音読み・訓読みで検索" value={query} onChange={e=>setQuery(e.target.value)}/>{normalized&&<div className="dictionary-results">{matches.map(k=><button key={k.literal} onClick={()=>onSelect(k.literal)}><b>{k.literal}</b><span>音 {k.onyomi.join("・")||"—"}</span><span>訓 {k.kunyomi.join("・")||"—"}</span></button>)}{!matches.length&&<p>一致する漢字がありません</p>}</div>}</section>}
function Notebook({entries,onSelect}:{entries:Record<string,Entry>;onSelect:(x:string)=>void}){const [q,setQ]=useState("");const [filter,setFilter]=useState("all");const list=Object.values(entries).filter(e=>(filter==="all"||e.status===filter)&&(e.key.includes(q)||e.reading.includes(q))).sort((a,b)=>b.learnedAt.localeCompare(a.learnedAt));return <section className="panel"><div className="eyebrow">漢字帳</div><h1>育てている言葉</h1><DictionaryLookup onSelect={onSelect}/><div className="filters"><input placeholder="登録済みの漢字・読み方で検索" value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">すべての状態</option><option value="learning">学習中</option><option value="known">覚えた</option><option value="review">復習が必要</option><option value="stable">安定</option></select></div><div className="table"><div className="tr th"><span>語・読み</span><span>状態</span><span>次回復習</span><span>確認 / 忘れ</span></div>{list.map(e=><button className="tr" key={e.key} onClick={()=>onSelect(e.key)}><span><b>{e.key}</b><small>{e.reading}</small></span><span><i className={`badge ${e.status}`}>{({learning:"学習中",known:"覚えた",review:"復習が必要",stable:"安定"} as Record<string,string>)[e.status]}</i></span><span>{e.nextReview}</span><span>{e.checks} / {e.forgot}</span></button>)}</div>{!list.length&&<div className="empty"><span>字</span><p>文章中の語をタップすると、ここに追加されます</p></div>}</section>}
function History({entries}:{entries:Record<string,Entry>}){const all=Object.values(entries);const max=Math.max(1,...all.map(e=>e.checks));return <section className="panel"><div className="eyebrow">学習履歴</div><h1>積み重ねが見える場所</h1><div className="stats compact"><article><span>登録した語</span><strong>{all.length}<small>語</small></strong></article><article><span>確認した回数</span><strong>{all.reduce((a,e)=>a+e.checks,0)}<small>回</small></strong></article><article><span>よく忘れる語</span><strong>{all.filter(e=>e.forgot>=2).length}<small>語</small></strong></article></div><h2 className="chart-title">言葉ごとの確認回数</h2><div className="chart">{all.slice(0,12).map(e=><div key={e.key}><span>{e.key}</span><i style={{width:`${Math.max(7,e.checks/max*100)}%`}}/><b>{e.checks}</b></div>)}</div>{!all.length&&<div className="empty"><p>学習を始めるとグラフが表示されます</p></div>}</section>}
function DataTools({entries,books,setEntries,setBooks,toast}:{entries:Record<string,Entry>;books:Book[];setEntries:(x:Record<string,Entry>)=>void;setBooks:(x:Book[])=>void;toast:(x:string)=>void}){const exp=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,entries,books},null,2)],{type:"application/json"}));a.download=`kanji-reading-${today()}.json`;a.click()};const imp=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));setEntries(d.entries||{});setBooks(d.books||[]);toast("データを復元しました")}catch{alert("JSONファイルを読み込めませんでした")}};r.readAsText(f)};return <div className="data-tools"><h2>データ管理</h2><div><button onClick={exp}>JSONを書き出す</button><label className="file-btn">JSONを読み込む<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&imp(e.target.files[0])}/></label></div><div className="danger"><button onClick={()=>confirm("漢字帳を初期化しますか？")&&setEntries({})}>漢字帳を初期化</button><button onClick={()=>confirm("読書履歴を初期化しますか？")&&setBooks([])}>読書履歴を初期化</button></div></div>}
