"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import schoolKanjiData from "./data/school-kanji.json";
import commonWordsData from "./data/common-words.json";
import { inferKanjiRun, isKanji } from "./furigana-engine";
import SourceNotice from "./source-notice";

type Status = "learning" | "known" | "review" | "stable";
type ReadingSource = "manual"|"saved"|"annotation"|"builtin"|"ambiguous"|"candidate";
type Entry = { key:string; reading:string; meaning?:string; status:Status; learnedAt:string; lastChecked:string; checks:number; forgot:number; nextReview:string; example:string; streak:number; readingSource?:ReadingSource };
type Book = { id:string; title:string; body:string; createdAt:string; lastRead:string; deletedAt?:string };
type Retention = "7"|"30"|"90"|"never";
type Tab = "home"|"input"|"reading"|"notebook"|"review"|"library"|"history"|"settings";
type KanjiInfo = { literal:string; grade:number; onyomi:string[]; kunyomi:string[]; meanings:string[] };
type ParsedUnit = { text:string; reading?:string; meaning?:string; source?:ReadingSource };

// KANJIDIC由来の常用漢字データから、小学校6学年と中学校相当（grade 8）を採用。
// AI注釈・熟語辞書・手動修正を優先し、それ以外には内蔵漢字辞書から推定読みを付ける。
const SCHOOL_KANJI:Record<string,KanjiInfo> = Object.fromEntries(
  (schoolKanjiData.characters as KanjiInfo[]).map(k=>[k.literal,k])
);
const kataToHira=(s:string)=>s.replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
const cleanReading=(s:string)=>kataToHira(s.replace(/[.\-]/g,""));
const readingCandidates=(k?:KanjiInfo)=>k?[...new Set([...k.onyomi,...k.kunyomi].map(cleanReading).filter(Boolean))]:[];

const SAMPLE = "[今日|きょう|today]は[学校|がっこう|school]の[図書館|としょかん|library]で[日本|にほん|Japan]の[歴史|れきし|history]について[勉強|べんきょう|studied]しました。[最初|さいしょ|at first]は[難しい|むずかしい|difficult][漢字|かんじ|kanji]が[多い|おおい|many]と[思いました|おもいました|thought]が、[少し|すこし|little by little]ずつ[読める|よめる|became able to read]ようになりました。";
const DICT:Record<string,string> = {
  ...(commonWordsData.words as Record<string,string>),
  // Context-sensitive app overrides take priority over the generated common-word dictionary.
  "今日":"きょう",
};
const WORD_READING_CANDIDATES:Record<string,string[]> = {
  ...(commonWordsData.readingCandidates as Record<string,string[]>),
  // Frequently encountered contextual readings that may not share JMdict's common-word tags.
  "人気":["にんき","ひとけ"],
  "大分":["だいぶ","おおいた"],
};
const BUILTIN_BY_FIRST = Object.entries(DICT).reduce<Record<string,string[]>>((index,[word])=>{
  (index[word[0]]??=[]).push(word);
  return index;
},{});
Object.values(BUILTIN_BY_FIRST).forEach(words=>words.sort((a,b)=>b.length-a.length));
const NAV:{id:Tab;label:string;icon:string}[] = [
  {id:"home",label:"ホーム",icon:"⌂"},{id:"input",label:"文章入力",icon:"＋"},{id:"reading",label:"リーディング",icon:"▤"},{id:"notebook",label:"漢字帳",icon:"字"},{id:"review",label:"復習",icon:"↻"},{id:"library",label:"ライブラリ",icon:"▣"},{id:"history",label:"学習履歴",icon:"⌁"},{id:"settings",label:"設定",icon:"⚙"}
];
type Lang = "ja"|"en"|"ru"|"fr"|"es";
const LANGS:{id:Lang;label:string}[]=[{id:"ja",label:"日本語"},{id:"en",label:"English"},{id:"ru",label:"Русский"},{id:"fr",label:"Français"},{id:"es",label:"Español"}];
const TX:Record<string,string[]>={
"漢字リーディング":["Kanji Reading","Чтение кандзи","Lecture des kanji","Lectura de kanji"],"今日も一歩ずつ":["One step today","Ещё один шаг","Un pas aujourd’hui","Un paso hoy"],
"ホーム":["Home","Главная","Accueil","Inicio"],"文章入力":["Add text","Ввод текста","Saisir un texte","Introducir texto"],"リーディング":["Reading","Чтение","Lecture","Lectura"],"漢字帳":["Kanji notebook","Словарь кандзи","Carnet de kanji","Cuaderno de kanji"],"復習":["Review","Повторение","Révision","Repaso"],"ライブラリ":["Library","Библиотека","Bibliothèque","Biblioteca"],"学習履歴":["Progress","Прогресс","Progression","Progreso"],"設定":["Settings","Настройки","Réglages","Ajustes"],
"おはようございます":["Welcome back","С возвращением","Bienvenue","Bienvenido"],"今日も、ひとつずつ。":["One word at a time.","По одному слову за раз.","Un mot à la fois.","Una palabra a la vez."],"読むほどに、ふりがなが静かに減っていきます。":["As you learn, furigana quietly fades away.","По мере обучения фуригана постепенно исчезает.","À mesure que vous apprenez, les furigana disparaissent.","A medida que aprendes, el furigana desaparece."],"文章を読む":["Read a text","Читать текст","Lire un texte","Leer un texto"],
"今日の復習":["Reviews today","На повторение","Révisions du jour","Repasos de hoy"],"復習を始める →":["Start review →","Начать →","Commencer →","Empezar →"],"覚えた語":["Words learned","Выучено","Mots appris","Palabras aprendidas"],"あなたの読める言葉":["Words you can read","Слова, которые вы читаете","Les mots que vous lisez","Palabras que puedes leer"],"学習中":["Learning","Изучается","En cours","Aprendiendo"],"焦らず育てましょう":["Grow at your pace","Учитесь в своём темпе","À votre rythme","A tu ritmo"],
"最近読んだ文章":["Recently read","Недавние тексты","Lectures récentes","Lecturas recientes"],"すべて見る":["View all","Показать все","Tout voir","Ver todo"],"はじめての方へ":["Getting started","Как начать","Bien démarrer","Primeros pasos"],"3ステップで始められます":["Start in three steps","Три простых шага","Trois étapes simples","Tres pasos sencillos"],"文章を貼り付ける":["Paste a text","Вставьте текст","Collez un texte","Pega un texto"],"ふりがなで読む":["Read with furigana","Читайте с фуриганой","Lisez avec les furigana","Lee con furigana"],"覚えたらタップ":["Tap when learned","Нажмите, когда выучили","Touchez quand c’est acquis","Toca cuando lo aprendas"],
"今日は何を読みますか？":["What will you read today?","Что вы прочитаете сегодня?","Que lirez-vous aujourd’hui ?","¿Qué vas a leer hoy?"],"タイトル":["Title","Заголовок","Titre","Título"],"日本語の文章":["Japanese text","Текст на японском","Texte japonais","Texto japonés"],"サンプルを読み込む":["Load sample","Загрузить пример","Charger l’exemple","Cargar ejemplo"],"入力を削除":["Clear","Очистить","Effacer","Borrar"],"ライブラリに保存":["Save to library","Сохранить","Enregistrer","Guardar"],"ふりがな付き文章に変換 →":["Add furigana →","Добавить фуригану →","Ajouter les furigana →","Añadir furigana →"],
"ふりがな":["Furigana","Фуригана","Furigana","Furigana"],"未学習だけ":["Unlearned only","Только новые","Non appris","Solo no aprendidos"],"すべて表示":["Show all","Показать все","Tout afficher","Mostrar todo"],"復習だけ":["Review only","Только повторение","À réviser","Solo repaso"],"クリックだけ":["On tap only","Только по нажатию","Au toucher","Solo al tocar"],"すべて非表示":["Hide all","Скрыть всё","Tout masquer","Ocultar todo"],"文章を編集":["Edit text","Редактировать","Modifier","Editar"],"保存する":["Save","Сохранить","Enregistrer","Guardar"],
"育てている言葉":["Words you are growing","Ваши изучаемые слова","Les mots que vous cultivez","Palabras que aprendes"],"漢字・読み方で検索":["Search word or reading","Поиск слова или чтения","Rechercher un mot ou une lecture","Buscar palabra o lectura"],"すべての状態":["All statuses","Все статусы","Tous les états","Todos los estados"],"覚えた":["Learned","Выучено","Acquis","Aprendido"],"復習が必要":["Needs review","Нужно повторить","À réviser","Necesita repaso"],"安定":["Stable","Закреплено","Stable","Estable"],"語・読み":["Word / reading","Слово / чтение","Mot / lecture","Palabra / lectura"],"状態":["Status","Статус","État","Estado"],"次回復習":["Next review","Следующее повторение","Prochaine révision","Próximo repaso"],
"復習モード":["Review mode","Режим повторения","Mode révision","Modo repaso"],"読み方を見る":["Show reading","Показать чтение","Voir la lecture","Ver lectura"],"分からなかった":["Didn't know","Не знал","Je ne savais pas","No lo sabía"],"少し迷った":["Hesitated","Сомневался","J’ai hésité","Dudé"],"分かった":["Knew it","Знал","Je savais","Lo sabía"],"すぐ分かった":["Knew instantly","Сразу знал","Immédiatement","Al instante"],"今日の復習は完了です":["Today's review is complete","Повторение завершено","Révision terminée","Repaso completado"],
"読書ライブラリ":["Reading library","Библиотека текстов","Bibliothèque de lecture","Biblioteca de lectura"],"保存した文章":["Saved texts","Сохранённые тексты","Textes enregistrés","Textos guardados"],"＋ 新しい文章":["＋ New text","＋ Новый текст","＋ Nouveau texte","＋ Nuevo texto"],"もう一度読む":["Read again","Читать снова","Relire","Leer de nuevo"],"削除":["Delete","Удалить","Supprimer","Eliminar"],
"積み重ねが見える場所":["See how far you have come","Посмотрите свой прогресс","Visualisez vos progrès","Mira cuánto has avanzado"],"登録した語":["Saved words","Сохранено слов","Mots enregistrés","Palabras guardadas"],"確認した回数":["Reading checks","Проверки чтения","Lectures vérifiées","Lecturas comprobadas"],"よく忘れる語":["Often forgotten","Часто забываются","Souvent oubliés","Olvidadas a menudo"],
"読みやすさとデータ":["Reading and data","Чтение и данные","Lecture et données","Lectura y datos"],"本文の文字サイズ":["Text size","Размер текста","Taille du texte","Tamaño del texto"],"行間":["Line spacing","Межстрочный интервал","Interligne","Interlineado"],"ダークテーマ":["Dark theme","Тёмная тема","Thème sombre","Tema oscuro"],"データ管理":["Data management","Управление данными","Gestion des données","Gestión de datos"],"JSONを書き出す":["Export JSON","Экспорт JSON","Exporter JSON","Exportar JSON"],"JSONを読み込む":["Import JSON","Импорт JSON","Importer JSON","Importar JSON"],
"学習する語":["Word to learn","Новое слово","Mot à apprendre","Palabra por aprender"],"読み未登録":["Reading not registered","Чтение не указано","Lecture non renseignée","Lectura no registrada"],"読み方を修正":["Edit reading","Изменить чтение","Modifier la lecture","Editar lectura"],"✓ 覚えた":["✓ Learned","✓ Выучено","✓ Acquis","✓ Aprendido"],"↻ 復習対象に戻す":["↻ Return to review","↻ Вернуть на повторение","↻ Remettre à réviser","↻ Volver a repasar"],"一度だけ読みを表示":["Show once","Показать один раз","Afficher une fois","Mostrar una vez"],"この文章では表示":["Show in this text","Показывать в этом тексте","Afficher dans ce texte","Mostrar en este texto"]};
Object.assign(TX, {
"語":[" words"," сл."," mots"," palabras"],"回":[" times"," раз"," fois"," veces"],"字":[" characters"," знаков"," caractères"," caracteres"],"文":["Text","Текст","Texte","Texto"],"日本語":["Japanese","Японский","Japonais","Japonés"],
"ホームへ":["Go to home","На главную","Aller à l’accueil","Ir al inicio"],"テーマ切替":["Switch theme","Сменить тему","Changer de thème","Cambiar tema"],"メインナビゲーション":["Main navigation","Основная навигация","Navigation principale","Navegación principal"],"閉じる":["Close","Закрыть","Fermer","Cerrar"],
"読みたい日本語を入力します":["Enter the Japanese text you want to read.","Введите японский текст для чтения.","Saisissez le texte japonais à lire.","Introduce el texto japonés que quieras leer."],"分からない語も止まらず読めます":["Keep reading even when a word is unfamiliar.","Читайте дальше, даже если слово незнакомо.","Continuez à lire même si un mot est inconnu.","Sigue leyendo aunque no conozcas una palabra."],"次からふりがなが消えます":["Its furigana will be hidden next time.","В следующий раз фуригана будет скрыта.","Les furigana seront masqués la prochaine fois.","La próxima vez se ocultará el furigana."],
"注釈付き文章入力":["Annotated text input","Ввод текста с аннотациями","Saisie de texte annoté","Entrada de texto anotado"],"自分で利用できる文章だけを入力してください。著作権に関する法律は国によって異なります。":["Only enter text you are permitted to use. Copyright laws vary by country.","Вводите только тексты, которые вы имеете право использовать. Законы об авторском праве различаются по странам.","Saisissez uniquement des textes que vous êtes autorisé à utiliser. Le droit d’auteur varie selon les pays.","Introduce únicamente textos que tengas derecho a utilizar. Las leyes de derechos de autor varían según el país."],
"普通の日本語を貼るだけで、AIなしでもふりがなを付けます":["Paste ordinary Japanese text to add furigana without AI","Вставьте обычный японский текст — фуригана добавится без ИИ","Collez un texte japonais ordinaire pour ajouter les furigana sans IA","Pega un texto japonés normal para añadir furigana sin IA"],"個人辞書と内蔵熟語を優先し、登録のない漢字にも内蔵漢字辞書から推定した読みを表示します。推定部分は点線で区別できます。":["Your personal dictionary and built-in words take priority. For other kanji, the built-in kanji dictionary suggests a reading, marked with a dotted underline.","Сначала используются личный словарь и встроенные слова. Для остальных кандзи встроенный словарь предлагает чтение, отмеченное пунктиром.","Le dictionnaire personnel et les mots intégrés sont prioritaires. Pour les autres kanji, le dictionnaire intégré propose une lecture signalée par un soulignement pointillé.","Se da prioridad al diccionario personal y a las palabras integradas. Para los demás kanji, el diccionario propone una lectura marcada con subrayado punteado."],"文章を外部へ送信しません。推定が違う場合は語を押して修正してください。その端末の個人辞書に保存され、次回から自動的に使われます。":["Your text is never sent outside this device. If a suggestion is wrong, tap the word to correct it. The correction is saved in this device’s personal dictionary.","Текст не отправляется за пределы устройства. Если чтение неверно, нажмите слово и исправьте его. Исправление сохранится в личном словаре этого устройства.","Le texte n’est jamais envoyé hors de l’appareil. Si une lecture est incorrecte, touchez le mot pour la corriger. La correction sera enregistrée dans le dictionnaire personnel de cet appareil.","El texto no se envía fuera del dispositivo. Si una lectura es incorrecta, toca la palabra para corregirla. La corrección se guardará en el diccionario personal del dispositivo."],
"意味と、文脈に合うより正確な読みも必要な場合はAI形式を使えます":["Use the optional AI format when you also need meanings and more context-sensitive readings","Используйте необязательный формат ИИ, если нужны значения и более точные чтения по контексту","Utilisez le format IA facultatif pour obtenir aussi le sens et une lecture plus précise selon le contexte","Usa el formato de IA opcional si también necesitas significados y lecturas más precisas según el contexto"],"日本語の語・ひらがなの読み・英語の意味を、すべて角括弧の中に入れます。通常の日本語文章も、そのまま利用できます。":["Put the Japanese word, hiragana reading, and English meaning inside the brackets. Ordinary Japanese text also works as it is.","Поместите японское слово, чтение хираганой и английское значение в скобки. Обычный японский текст также можно использовать без изменений.","Placez le mot japonais, sa lecture en hiragana et son sens anglais entre crochets. Un texte japonais ordinaire peut aussi être utilisé tel quel.","Coloca la palabra japonesa, la lectura en hiragana y el significado en inglés entre corchetes. También puedes usar texto japonés normal sin modificarlo."],"✓ コピーしました":["✓ Copied","✓ Скопировано","✓ Copié","✓ Copiado"],"新形式のAI用英語プロンプトをコピー":["Copy the English AI-format prompt","Скопировать английский промпт для формата ИИ","Copier le prompt anglais pour le format IA","Copiar el prompt en inglés para el formato de IA"],"辞書・登録済みの読み：":["Dictionary/saved readings: ","Словарные/сохранённые чтения: ","Lectures du dictionnaire/enregistrées : ","Lecturas del diccionario/guardadas: "],"自動推定：":["Automatic suggestions: ","Автоматические варианты: ","Suggestions automatiques : ","Sugerencias automáticas: "],"読書画面を開く →":["Open reading view →","Открыть режим чтения →","Ouvrir la lecture →","Abrir la vista de lectura →"],
"縦/横":["Vertical / horizontal","Вертикально / горизонтально","Vertical / horizontal","Vertical / horizontal"],"辞書・登録済みの読み":["Dictionary or saved reading","Словарное или сохранённое чтение","Lecture du dictionnaire ou enregistrée","Lectura del diccionario o guardada"],"点線はAIを使わない推定読み":["Dotted underline: non-AI reading suggestion","Пунктир: чтение, предложенное без ИИ","Pointillés : lecture suggérée sans IA","Punteado: lectura sugerida sin IA"],"語をタップすると、読み方と学習状態を変更できます":["Tap a word to change its reading or learning status.","Нажмите слово, чтобы изменить чтение или статус изучения.","Touchez un mot pour modifier sa lecture ou son état d’apprentissage.","Toca una palabra para cambiar su lectura o estado de aprendizaje."],"読書を終了":["End reading","Закончить чтение","Terminer la lecture","Terminar lectura"],
"新しい文章を読んで、言葉を育てましょう。":["Read a new text to keep building your vocabulary.","Читайте новые тексты и расширяйте словарный запас.","Lisez un nouveau texte pour enrichir votre vocabulaire.","Lee un texto nuevo para seguir ampliando tu vocabulario."],"本文削除済み":["Text deleted","Текст удалён","Texte supprimé","Texto eliminado"],"本文は保存期限または手動操作により削除されました。":["The text was deleted when its retention period expired or by a manual action.","Текст удалён по истечении срока хранения или вручную.","Le texte a été supprimé à l’expiration de sa durée de conservation ou manuellement.","El texto se eliminó al vencer el plazo de conservación o de forma manual."],"まだ文章が保存されていません":["No texts have been saved yet.","Тексты ещё не сохранены.","Aucun texte n’a encore été enregistré.","Todavía no hay textos guardados."],"登録":["saved","сохранено","enregistré","guardado"],
"内蔵漢字辞書":["Built-in kanji dictionary","Встроенный словарь кандзи","Dictionnaire de kanji intégré","Diccionario de kanji integrado"],"義務教育の常用漢字":["school-taught jōyō kanji","кандзи дзёё школьной программы","kanji jōyō du programme scolaire","kanji jōyō del programa escolar"],"漢字・音読み・訓読みで検索":["Search by kanji, on-reading, or kun-reading","Поиск по кандзи, онъёми или кунъёми","Rechercher par kanji, on’yomi ou kun’yomi","Buscar por kanji, on’yomi o kun’yomi"],"登録済みの漢字・読み方で検索":["Search saved kanji or readings","Поиск сохранённых кандзи или чтений","Rechercher les kanji ou lectures enregistrés","Buscar kanji o lecturas guardadas"],"一致する漢字がありません":["No matching kanji.","Подходящих кандзи нет.","Aucun kanji correspondant.","No hay kanji coincidentes."],"音":["On","Он","On","On"],"訓":["Kun","Кун","Kun","Kun"],"音読み":["On-reading","Онъёми","On’yomi","On’yomi"],"訓読み":["Kun-reading","Кунъёми","Kun’yomi","Kun’yomi"],"確認 / 忘れ":["Checks / forgotten","Проверки / забыто","Vérifications / oublis","Comprobaciones / olvidos"],"文章中の語をタップすると、ここに追加されます":["Tap a word in the text to add it here.","Нажмите слово в тексте, чтобы добавить его сюда.","Touchez un mot dans le texte pour l’ajouter ici.","Toca una palabra del texto para añadirla aquí."],"言葉ごとの確認回数":["Checks by word","Проверки по словам","Vérifications par mot","Comprobaciones por palabra"],"学習を始めるとグラフが表示されます":["The chart will appear after you begin learning.","График появится после начала обучения.","Le graphique apparaîtra lorsque vous commencerez à apprendre.","El gráfico aparecerá cuando empieces a aprender."],
"目の負担を抑えます":["Reduces eye strain","Снижает нагрузку на глаза","Réduit la fatigue visuelle","Reduce la fatiga visual"],"本文の保存と著作権":["Text retention and copyright","Хранение текста и авторское право","Conservation du texte et droit d’auteur","Conservación del texto y derechos de autor"],"標準では、最後に読んでから30日後に本文だけを削除します。学習した語・読み・復習記録は残ります。":["By default, only the text is deleted 30 days after it was last read. Learned words, readings, and review records remain.","По умолчанию через 30 дней после последнего чтения удаляется только текст. Изученные слова, чтения и история повторений сохраняются.","Par défaut, seul le texte est supprimé 30 jours après la dernière lecture. Les mots appris, les lectures et l’historique des révisions sont conservés.","De forma predeterminada, solo el texto se elimina 30 días después de la última lectura. Las palabras aprendidas, las lecturas y el historial de repaso se conservan."],"本文の保存期間":["Text retention period","Срок хранения текста","Durée de conservation du texte","Plazo de conservación del texto"],"7日":["7 days","7 дней","7 jours","7 días"],"30日（標準）":["30 days (default)","30 дней (по умолчанию)","30 jours (par défaut)","30 días (predeterminado)"],"90日":["90 days","90 дней","90 jours","90 días"],"削除しない":["Never delete","Не удалять","Ne jamais supprimer","No eliminar"],"著作権の問題はそれぞれの国によって異なります。保存する文章については、ご自身で責任を持って管理してください。":["Copyright rules vary by country. You are responsible for managing any text you choose to retain.","Правила авторского права различаются по странам. Вы несёте ответственность за сохранённые тексты.","Les règles de droit d’auteur varient selon les pays. Vous êtes responsable des textes que vous choisissez de conserver.","Las normas de derechos de autor varían según el país. Eres responsable de los textos que decidas conservar."],"保存していない文章は読書終了時に破棄する":["Discard unsaved text when reading ends","Удалять несохранённый текст после чтения","Supprimer le texte non enregistré à la fin de la lecture","Descartar el texto no guardado al terminar la lectura"],"漢字帳と復習記録は残ります。":["The kanji notebook and review records remain.","Словарь кандзи и история повторений сохраняются.","Le carnet de kanji et l’historique des révisions sont conservés.","El cuaderno de kanji y el historial de repaso se conservan."],"今すぐ本文を削除":["Delete text now","Удалить текст сейчас","Supprimer le texte maintenant","Eliminar texto ahora"],"内蔵漢字辞書：":["Built-in kanji dictionary: ","Встроенный словарь кандзи: ","Dictionnaire de kanji intégré : ","Diccionario de kanji integrado: "],"個人辞書：":["Personal dictionary: ","Личный словарь: ","Dictionnaire personnel : ","Diccionario personal: "],
"内蔵一般語辞書：":["Built-in common-word dictionary: ","Встроенный словарь общеупотребительных слов: ","Dictionnaire de mots courants intégré : ","Diccionario integrado de palabras comunes: "],
"手動で修正した読み":["Manually corrected reading","Чтение исправлено вручную","Lecture corrigée manuellement","Lectura corregida manualmente"],"個人辞書に保存済み":["Saved in personal dictionary","Сохранено в личном словаре","Enregistré dans le dictionnaire personnel","Guardado en el diccionario personal"],"入力された注釈":["Imported annotation","Введённая аннотация","Annotation importée","Anotación importada"],"内蔵熟語辞書":["Built-in word dictionary","Встроенный словарь слов","Dictionnaire de mots intégré","Diccionario de palabras integrado"],"内蔵漢字辞書による推定読み":["Reading suggested by built-in kanji dictionary","Чтение предложено встроенным словарём кандзи","Lecture suggérée par le dictionnaire de kanji intégré","Lectura sugerida por el diccionario de kanji integrado"],"読みはまだ確定していません":["The reading has not been confirmed yet.","Чтение ещё не подтверждено.","La lecture n’est pas encore confirmée.","La lectura aún no está confirmada."],"候補から選ぶ":["Choose a suggestion","Выберите вариант","Choisir une suggestion","Elegir una sugerencia"],"内蔵漢字辞書の別候補":["Other built-in dictionary suggestions","Другие варианты встроенного словаря","Autres suggestions du dictionnaire intégré","Otras sugerencias del diccionario integrado"],"ここにある読みは候補です。熟語・送り仮名・文脈に合うものがない場合は、下の「読み方を修正」から正しい読みを入力してください。":["These readings are suggestions. If none fits the word, okurigana, and context, use “Edit reading” below.","Это варианты чтения. Если ни один не подходит слову, окуригане и контексту, используйте «Изменить чтение» ниже.","Ces lectures sont des suggestions. Si aucune ne convient au mot, aux okurigana et au contexte, utilisez « Modifier la lecture » ci-dessous.","Estas lecturas son sugerencias. Si ninguna encaja con la palabra, el okurigana y el contexto, usa «Editar lectura» abajo."],"一度だけ表示した読みは、5秒後に再び隠れます。":["A one-time reading is hidden again after five seconds.","Однократно показанное чтение снова скроется через пять секунд.","Une lecture affichée une fois sera de nouveau masquée après cinq secondes.","Una lectura mostrada una vez volverá a ocultarse después de cinco segundos."],"読みを確定すると、個人辞書として次回の文章でも使われます。":["Once confirmed, the reading is saved in your personal dictionary for future texts.","После подтверждения чтение сохранится в личном словаре для будущих текстов.","Une fois confirmée, la lecture est enregistrée dans votre dictionnaire personnel pour les prochains textes.","Una vez confirmada, la lectura se guardará en tu diccionario personal para textos futuros."],
"辞書の出典とライセンス":["Dictionary sources and licences","Источники и лицензии словаря","Sources et licences du dictionnaire","Fuentes y licencias del diccionario"],"データを復元しました":["Data restored","Данные восстановлены","Données restaurées","Datos restaurados"],"JSONファイルを読み込めませんでした":["The JSON file could not be read.","Не удалось прочитать файл JSON.","Impossible de lire le fichier JSON.","No se pudo leer el archivo JSON."],"漢字帳を初期化":["Reset kanji notebook","Сбросить словарь кандзи","Réinitialiser le carnet de kanji","Restablecer cuaderno de kanji"],"読書履歴を初期化":["Reset reading history","Сбросить историю чтения","Réinitialiser l’historique de lecture","Restablecer historial de lectura"]
,
"義務教育で扱う常用漢字の音読み・訓読みを収録しています。登録のない漢字にもAIなしで推定読みを表示します。点線の語は、熟語や文脈によって読みが異なる可能性があります。修正した語は個人辞書として保存され、次回から最優先で使われます。":["Includes on- and kun-readings for school-taught jōyō kanji. Unregistered kanji receive non-AI reading suggestions. Dotted words may have a different reading in compounds or context. Corrections are saved in your personal dictionary and used first next time.","Содержит онъёми и кунъёми кандзи дзёё школьной программы. Для незарегистрированных кандзи чтение предлагается без ИИ. Пунктир означает, что чтение может меняться в слове или контексте. Исправления сохраняются в личном словаре и получают приоритет.","Contient les lectures on et kun des kanji jōyō du programme scolaire. Les kanji non enregistrés reçoivent une suggestion sans IA. Les mots pointillés peuvent avoir une autre lecture selon le composé ou le contexte. Les corrections sont enregistrées dans votre dictionnaire personnel et deviennent prioritaires.","Incluye lecturas on y kun de los kanji jōyō del programa escolar. Los kanji no registrados reciben sugerencias sin IA. Las palabras punteadas pueden tener otra lectura según el compuesto o el contexto. Las correcciones se guardan en el diccionario personal y tienen prioridad."],
"先に正しい読み方を選択または入力してください":["Select or enter the correct reading first.","Сначала выберите или введите правильное чтение.","Sélectionnez ou saisissez d’abord la lecture correcte.","Selecciona o introduce primero la lectura correcta."],"覚えた語に登録しました：":["Marked as learned: ","Отмечено как выученное: ","Marqué comme acquis : ","Marcado como aprendido: "],"復習に戻しました：":["Returned to review: ","Возвращено на повторение: ","Remis en révision : ","Devuelto al repaso: "],"個人辞書に保存しました：":["Saved in personal dictionary: ","Сохранено в личном словаре: ","Enregistré dans le dictionnaire personnel : ","Guardado en el diccionario personal: "],"保存する本文がありません":["There is no text to save.","Нет текста для сохранения.","Aucun texte à enregistrer.","No hay texto para guardar."],"無題の文章":["Untitled text","Текст без названия","Texte sans titre","Texto sin título"],"読書ライブラリに保存しました":["Saved to the reading library.","Сохранено в библиотеке текстов.","Enregistré dans la bibliothèque de lecture.","Guardado en la biblioteca de lectura."],"この文章の本文は保存期限により削除されています":["This text was deleted when its retention period expired.","Этот текст удалён по истечении срока хранения.","Ce texte a été supprimé à l’expiration de sa durée de conservation.","Este texto se eliminó al vencer el plazo de conservación."],
"個人辞書に登録する単語・熟語を入力してください":["Enter the word or expression to save in your personal dictionary.","Введите слово или выражение для сохранения в личном словаре.","Saisissez le mot ou l’expression à enregistrer dans votre dictionnaire personnel.","Introduce la palabra o expresión que quieras guardar en tu diccionario personal."],"現在の本文にある語を入力してください":["Enter a word that appears in the current text.","Введите слово из текущего текста.","Saisissez un mot présent dans le texte actuel.","Introduce una palabra que aparezca en el texto actual."],"正しい読み方をひらがなで入力してください":["Enter the correct reading in hiragana.","Введите правильное чтение хираганой.","Saisissez la lecture correcte en hiragana.","Introduce la lectura correcta en hiragana."],"保存していない本文を破棄しました":["Unsaved text discarded.","Несохранённый текст удалён.","Texte non enregistré supprimé.","Texto no guardado descartado."],"本文だけを削除しました":["Text content deleted; learning records were kept.","Текст удалён; учебные записи сохранены.","Texte supprimé ; les données d’apprentissage ont été conservées.","Texto eliminado; se conservaron los registros de aprendizaje."],"次回の復習日を更新しました":["Next review date updated.","Дата следующего повторения обновлена.","Date de la prochaine révision mise à jour.","Fecha del próximo repaso actualizada."],
"著作権の問題はそれぞれの国によって異なります。本文を期限なく保存することについて、ご自身で責任を持ちますか？":["Copyright rules vary by country. Do you accept responsibility for retaining this text indefinitely?","Правила авторского права различаются по странам. Вы принимаете ответственность за бессрочное хранение этого текста?","Les règles de droit d’auteur varient selon les pays. Acceptez-vous la responsabilité de conserver ce texte sans limite de durée ?","Las normas de derechos de autor varían según el país. ¿Aceptas la responsabilidad de conservar este texto indefinidamente?"],"本文を自動削除しない設定にしました":["Automatic text deletion disabled.","Автоматическое удаление текста отключено.","Suppression automatique du texte désactivée.","Eliminación automática del texto desactivada."],"本文を自動削除します：":["Text will be deleted automatically after ","Текст будет автоматически удалён через ","Le texte sera supprimé automatiquement après ","El texto se eliminará automáticamente después de "],"日後":[" days"," дней"," jours"," días"],"保存中の本文をすべて削除しますか？ 学習した語・読み・復習記録は残ります。":["Delete all saved text content? Learned words, readings, and review records will remain.","Удалить все сохранённые тексты? Изученные слова, чтения и история повторений сохранятся.","Supprimer tout le contenu des textes enregistrés ? Les mots appris, les lectures et l’historique des révisions seront conservés.","¿Eliminar todo el contenido de los textos guardados? Las palabras aprendidas, las lecturas y el historial de repaso se conservarán."],
"本文を自動削除しない設定です。学習記録は残ります。":["Text will not be deleted automatically. Learning records remain.","Текст не будет удаляться автоматически. Учебные записи сохраняются.","Le texte ne sera pas supprimé automatiquement. Les données d’apprentissage sont conservées.","El texto no se eliminará automáticamente. Los registros de aprendizaje se conservan."],"本文は最後に読んだ日から":["Text is deleted automatically","Текст автоматически удаляется","Le texte est supprimé automatiquement","El texto se elimina automáticamente"],"日後に自動削除されます。学習記録は残ります。":["days after it was last read. Learning records remain.","дней после последнего чтения. Учебные записи сохраняются.","jours après la dernière lecture. Les données d’apprentissage sont conservées.","días después de la última lectura. Los registros de aprendizaje se conservan."],"漢字帳を初期化しますか？":["Reset the kanji notebook?","Сбросить словарь кандзи?","Réinitialiser le carnet de kanji ?","¿Restablecer el cuaderno de kanji?"],"読書履歴を初期化しますか？":["Reset the reading history?","Сбросить историю чтения?","Réinitialiser l’historique de lecture ?","¿Restablecer el historial de lectura?"]
,
"保存した文章がここに並びます":["Your saved texts will appear here.","Сохранённые тексты появятся здесь.","Vos textes enregistrés apparaîtront ici.","Tus textos guardados aparecerán aquí."],"最初の文章を読む":["Read your first text","Прочитать первый текст","Lire votre premier texte","Leer tu primer texto"],"← 文章を編集":["← Edit text","← Редактировать текст","← Modifier le texte","← Editar texto"],"候補":[" suggestions"," вариантов"," suggestions"," sugerencias"],"に読書":[" read"," прочитано"," lu"," leído"],"内蔵漢字辞書を検索":["Search built-in kanji dictionary","Поиск во встроенном словаре кандзи","Rechercher dans le dictionnaire de kanji intégré","Buscar en el diccionario de kanji integrado"],"読み候補を確認":["check reading suggestions","проверить варианты чтения","vérifier les suggestions de lecture","comprobar sugerencias de lectura"],"読みと学習状態を確認":["check reading and learning status","проверить чтение и статус изучения","vérifier la lecture et l’état d’apprentissage","comprobar lectura y estado de aprendizaje"]
,
"文脈で読みが変わる語":["Reading varies by context","Чтение зависит от контекста","Lecture variable selon le contexte","La lectura depende del contexto"],"この語には複数の読みがあります。文に合う読みを選んでください。":["This word has more than one reading. Choose the one that fits the sentence.","У этого слова несколько чтений. Выберите подходящее по контексту.","Ce mot a plusieurs lectures. Choisissez celle qui convient à la phrase.","Esta palabra tiene varias lecturas. Elige la que corresponda a la frase."],"熟語辞書の読み候補":["Word-dictionary reading choices","Варианты чтения из словаря","Lectures proposées par le dictionnaire","Opciones de lectura del diccionario"],"複数候補の印":["Multiple-reading marker","Метка нескольких чтений","Marque de lectures multiples","Marca de varias lecturas"]
});
const tr=(lang:Lang,key:string)=>lang==="ja"?key:(TX[key]?.[{en:0,ru:1,fr:2,es:3}[lang]]||key);
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const expired=(date:string,days:number)=>Date.now()-new Date(`${date}T00:00:00`).getTime()>=days*86400000;

export default function Home(){
  const [tab,setTab]=useState<Tab>("home"); const [text,setText]=useState(SAMPLE); const [title,setTitle]=useState("図書館での一日");
  const [entries,setEntries]=useState<Record<string,Entry>>({}); const [books,setBooks]=useState<Book[]>([]); const [selected,setSelected]=useState<string|null>(null);
  const [temp,setTemp]=useState<string[]>([]); const [session,setSession]=useState<string[]>([]); const [mode,setMode]=useState("unknown");
  const [fontSize,setFontSize]=useState(25); const [lineHeight,setLineHeight]=useState(2.35); const [dark,setDark]=useState(false); const [vertical,setVertical]=useState(false);
  const [reviewIndex,setReviewIndex]=useState(0); const [showAnswer,setShowAnswer]=useState(false); const [notice,setNotice]=useState(""); const [hydrated,setHydrated]=useState(false); const [lang,setLang]=useState<Lang>("ja"); const [copied,setCopied]=useState(false);
  const [retention,setRetention]=useState<Retention>("30"); const [discardUnsaved,setDiscardUnsaved]=useState(false); const [draftSaved,setDraftSaved]=useState(false); const [textUpdatedAt,setTextUpdatedAt]=useState(today());
  useEffect(()=>{queueMicrotask(()=>{try{const savedEntries=JSON.parse(localStorage.getItem("kanji-reader-entries")||"{}");const savedBooks:Book[]=JSON.parse(localStorage.getItem("kanji-reader-books")||"[]");const s=JSON.parse(localStorage.getItem("kanji-reader-settings")||"{}");const keep:Retention=s.retention||"30";const days=keep==="never"?null:Number(keep);const currentExpired=!!(days&&s.text&&s.textUpdatedAt&&expired(s.textUpdatedAt,days));const bodyExpired=savedBooks.some(b=>!!b.body&&!!days&&expired(b.lastRead,days));setEntries(currentExpired||bodyExpired?Object.fromEntries(Object.entries(savedEntries).map(([k,v])=>[k,{...(v as Entry),example:""}])):savedEntries);setBooks(savedBooks.map(b=>b.body&&days&&expired(b.lastRead,days)?{...b,body:"",deletedAt:today()}:b));if(s.mode)setMode(s.mode);if(s.fontSize)setFontSize(s.fontSize);if(s.lineHeight)setLineHeight(s.lineHeight);if(s.dark)setDark(s.dark);if(s.lang)setLang(s.lang);setRetention(keep);setDiscardUnsaved(!!s.discardUnsaved);if(currentExpired){setText("");setTitle("");setDraftSaved(false)}else{if(s.text!==undefined)setText(s.text);if(s.title)setTitle(s.title);setDraftSaved(!!s.draftSaved)}if(s.textUpdatedAt)setTextUpdatedAt(s.textUpdatedAt)}catch{}setHydrated(true)})},[]);
  useEffect(()=>{if(!hydrated)return;localStorage.setItem("kanji-reader-entries",JSON.stringify(entries));localStorage.setItem("kanji-reader-books",JSON.stringify(books));localStorage.setItem("kanji-reader-settings",JSON.stringify({mode,fontSize,lineHeight,dark,lang,text,title,retention,discardUnsaved,draftSaved,textUpdatedAt}))},[entries,books,mode,fontSize,lineHeight,dark,lang,text,title,retention,discardUnsaved,draftSaved,textUpdatedAt,hydrated]);
  useEffect(()=>{document.documentElement.lang=lang;const idx={en:0,ru:1,fr:2,es:3} as const;const reverse=new Map<string,string>();Object.entries(TX).forEach(([ja,a])=>{reverse.set(ja,ja);a.forEach(x=>reverse.set(x,ja))});const translate=(value:string)=>{const base=reverse.get(value)||value;return lang==="ja"?base:TX[base]?.[idx[lang]]||base};const run=()=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(w.nextNode())nodes.push(w.currentNode as Text);nodes.forEach(n=>{if(n.parentElement?.closest(".reading-text,ruby,rt,textarea,input,code"))return;const raw=n.nodeValue||"",s=raw.trim(),out=translate(s);if(out!==s)n.nodeValue=raw.replace(s,out)});document.querySelectorAll<HTMLElement>("[placeholder],[aria-label],[title]").forEach(el=>{["placeholder","aria-label","title"].forEach(name=>{const value=el.getAttribute(name);if(value)el.setAttribute(name,translate(value))})})};run();const ob=new MutationObserver(run);ob.observe(document.body,{childList:true,subtree:true});return()=>ob.disconnect()},[lang,tab,selected,showAnswer]);
  const due=useMemo(()=>Object.values(entries).filter(e=>e.status==="review"||e.nextReview<=today()),[entries]);
  const known=Object.values(entries).filter(e=>e.status==="known"||e.status==="stable").length;
  const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2200)};
  // 個人辞書（これまでに保存・修正した語）を最優先し、その次に内蔵熟語を長い順で照合する。
  // 辞書にない漢字列にも、KANJIDIC2の代表的な音訓から「推定読み」を付ける。
  // 推定は点線で区別し、利用者が直した読みは次回から個人辞書として優先する。
  const personalWords=useMemo(()=>Object.keys(entries).filter(w=>entries[w]?.reading).sort((a,b)=>b.length-a.length),[entries]);
  const parseLegacy=(s:string)=>{const out:ParsedUnit[]=[];let i=0;while(i<s.length){const personal=personalWords.find(x=>s.startsWith(x,i));if(personal){out.push({text:personal,reading:entries[personal].reading,meaning:entries[personal].meaning,source:"saved"});i+=personal.length;continue}const builtin=(BUILTIN_BY_FIRST[s[i]]||[]).find(x=>s.startsWith(x,i));if(builtin){out.push({text:builtin,reading:DICT[builtin],source:(WORD_READING_CANDIDATES[builtin]?.length||0)>1?"ambiguous":"builtin"});i+=builtin.length;continue}const c=s[i];if(isKanji(c)){let end=i+1;while(end<s.length&&isKanji(s[end]))end++;const word=s.slice(i,end);const following=s.slice(end).match(/^[ぁ-んー]+/)?.[0]||"";const reading=inferKanjiRun(word,SCHOOL_KANJI,following);out.push({text:word,reading:reading||undefined,source:"candidate"});i=end;continue}out.push({text:c});i++}return out};
  // 推奨形式は「[表記|よみ|意味]」。表記そのものも角括弧内に入るため、
  // 助詞や前の文節を誤ってrubyへ取り込まない。既存データを守るため、
  // 従来の「語[よみ|意味]」と意味を省略した形式も引き続き解析する。
  const parse=(s:string)=>{const out:ParsedUnit[]=[];const pattern=/\[([^|\]\n]+)\|([^|\]\n]+)(?:\|([^\]\n]+))?\]|([々一-龯][々一-龯ぁ-んァ-ヶー]*)\[([^\]|\n]+)(?:\|([^\]\n]+))?\]/g;let cursor=0;for(const match of s.matchAll(pattern)){const start=match.index??0;if(start>cursor)out.push(...parseLegacy(s.slice(cursor,start)));const modern=match[1]!==undefined;out.push({text:(modern?match[1]:match[4]).trim(),reading:(modern?match[2]:match[5]).trim(),meaning:(modern?match[3]:match[6])?.trim(),source:"annotation"});cursor=start+match[0].length}if(cursor<s.length)out.push(...parseLegacy(s.slice(cursor)));return out};
  const parsed=parse(text);
  const annotations=Object.fromEntries(parsed.filter(p=>p.reading).map(p=>[p.text,{reading:p.reading||"",meaning:p.meaning||""}]));
  const readingFor=(word:string)=>entries[word]?.reading||annotations[word]?.reading||DICT[word]||"";
  const sourceFor=(word:string):ReadingSource=>entries[word]?.readingSource||((entries[word]?.reading)?"saved":parsed.find(p=>p.text===word)?.source)||"candidate";
  const sourceLabel=(source:ReadingSource)=>tr(lang,({manual:"手動で修正した読み",saved:"個人辞書に保存済み",annotation:"入力された注釈",builtin:"内蔵熟語辞書",ambiguous:"文脈で読みが変わる語",candidate:"内蔵漢字辞書による推定読み"} as Record<ReadingSource,string>)[source]);
  const visible=(w:string)=>{const e=entries[w];if(temp.includes(w)||session.includes(w))return true;if(mode==="all")return true;if(mode==="none"||mode==="click")return false;if(mode==="review")return e?.status==="review"||!!e&&e.nextReview<=today();return !e||e.status==="learning"||e.status==="review"||e.nextReview<=today()};
  const upsert=(word:string,status:Status)=>{const reading=readingFor(word);if(!reading){toast(tr(lang,"先に正しい読み方を選択または入力してください"));return}const old=entries[word];setEntries({...entries,[word]:{key:word,reading,meaning:old?.meaning||annotations[word]?.meaning||"",status,learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:(old?.checks||0)+(status==="known"?1:0),forgot:(old?.forgot||0)+(status==="review"?1:0),nextReview:addDays(status==="review"?1:status==="known"?3:7),example:text,streak:status==="known"?(old?.streak||0)+1:0,readingSource:old?.readingSource||sourceFor(word)}});setSelected(null);toast(status==="known"?tr(lang,"覚えた語に登録しました：")+word:tr(lang,"復習に戻しました：")+word)};
  const changeReading=(word:string)=>{const proposed=sourceFor(word)==="candidate"?prompt(tr(lang,"個人辞書に登録する単語・熟語を入力してください"),word):word;if(proposed===null)return;const target=proposed.trim();if(!target)return;if(!text.includes(target)){toast(tr(lang,"現在の本文にある語を入力してください"));return}const r=prompt(tr(lang,"正しい読み方をひらがなで入力してください"),entries[target]?.reading||readingFor(target));if(r!==null&&r.trim()){const old=entries[target];setEntries({...entries,[target]:{key:target,reading:cleanReading(r.trim()),meaning:old?.meaning||annotations[target]?.meaning||"",status:old?.status||"learning",learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:old?.checks||0,forgot:old?.forgot||0,nextReview:old?.nextReview||addDays(1),example:text,streak:old?.streak||0,readingSource:"manual"}});setSelected(null);toast(tr(lang,"個人辞書に保存しました：")+target)}};
  const chooseReading=(word:string,reading:string)=>{const old=entries[word];setEntries({...entries,[word]:{key:word,reading:cleanReading(reading),meaning:old?.meaning||annotations[word]?.meaning||"",status:old?.status||"learning",learnedAt:old?.learnedAt||today(),lastChecked:today(),checks:old?.checks||0,forgot:old?.forgot||0,nextReview:old?.nextReview||addDays(1),example:text,streak:old?.streak||0,readingSource:"manual"}});toast(tr(lang,"個人辞書に保存しました：")+word)};
  const saveBook=()=>{if(!text.trim()){toast(tr(lang,"保存する本文がありません"));return}const b:Book={id:crypto.randomUUID(),title:title||tr(lang,"無題の文章"),body:text,createdAt:today(),lastRead:today()};setBooks([b,...books]);setDraftSaved(true);setTextUpdatedAt(today());toast(tr(lang,"読書ライブラリに保存しました"))};
  const startReading=()=>{setTextUpdatedAt(today());setTab("reading");setSelected(null)};
  const openBook=(book:Book)=>{if(!book.body){toast(tr(lang,"この文章の本文は保存期限により削除されています"));return}setBooks(books.map(b=>b.id===book.id?{...b,lastRead:today()}:b));setTitle(book.title);setText(book.body);setTextUpdatedAt(today());setDraftSaved(true);setTab("reading")};
  const navigate=(next:Tab)=>{if(tab==="reading"&&next!=="reading"&&discardUnsaved&&!draftSaved){setText("");setTitle("");setTextUpdatedAt(today());setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])));toast(tr(lang,"保存していない本文を破棄しました"))}setTab(next);setSelected(null)};
  const updateRetention=(value:Retention)=>{if(value==="never"&&!confirm(tr(lang,"著作権の問題はそれぞれの国によって異なります。本文を期限なく保存することについて、ご自身で責任を持ちますか？")))return;setRetention(value);if(value!=="never"){const days=Number(value);const purged=books.some(b=>b.body&&expired(b.lastRead,days));setBooks(books.map(b=>b.body&&expired(b.lastRead,days)?{...b,body:"",deletedAt:today()}:b));if(text&&expired(textUpdatedAt,days)){setText("");setTitle("");setDraftSaved(false)}if(purged)setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])))}toast(value==="never"?tr(lang,"本文を自動削除しない設定にしました"):tr(lang,"本文を自動削除します：")+value+tr(lang,"日後"))};
  const deleteAllBodies=()=>{if(!confirm(tr(lang,"保存中の本文をすべて削除しますか？ 学習した語・読み・復習記録は残ります。")))return;setText("");setTitle("");setDraftSaved(false);setTextUpdatedAt(today());setBooks(books.map(b=>({...b,body:"",deletedAt:today()})));setEntries(Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{...v,example:""}])));toast(tr(lang,"本文だけを削除しました"))};
  const copyPrompt=async()=>{const prompt=`Rewrite the Japanese text below for use in a Japanese reading-learning application.

First, silently divide each sentence into natural Japanese bunsetsu (文節). Then identify the exact word or meaningful expression containing kanji inside each bunsetsu. Annotate only that kanji-containing lexical unit. Never attach a preceding particle, auxiliary expression, or unrelated hiragana from the previous part of the sentence to the annotated word.

For every word or expression that contains kanji, use exactly this format:

[Japanese surface text|hiragana reading|short contextual meaning in English]

Example:

[今日|きょう|today]は[学校|がっこう|school]の[図書館|としょかん|library]で[日本|にほん|Japan]の[歴史|れきし|history]について[勉強|べんきょう|studied]しました。

The entire annotated unit, including the original Japanese surface text, must be placed inside the square brackets.

Correct:

[今回|こんかい|this time]の[移民急増|いみんきゅうぞう|sharp increase in immigration]は[犯罪組織|はんざいそしき|criminal organization]

Incorrect:

今回[こんかい|this time]の移民急増[いみんきゅうぞう|sharp increase in immigration]

Follow these rules carefully:

1. Before annotating, silently determine the bunsetsu boundaries and the word boundaries within each bunsetsu.
2. Annotate every word or meaningful expression that contains kanji.
3. Put the exact Japanese surface text, its reading, and its meaning together inside one pair of square brackets. Never place the Japanese surface text outside the brackets.
4. Use the reading required by the actual sentence context.
5. Do not determine readings by mechanically separating individual kanji.
6. Prefer complete words and compounds, such as [今日|きょう|today], [図書館|としょかん|library], and [日本|にほん|Japan].
7. Keep okurigana that belongs to the word inside the Japanese surface field, such as [難しい|むずかしい|difficult] and [読める|よめる|can read]. Do not include following auxiliaries unless they form one meaningful expression that should be learned together.
8. Write readings entirely in hiragana. Do not use romaji or IPA.
9. Give one short English meaning that fits the word in that sentence. Do not list multiple dictionary meanings.
10. Preserve the original wording, word order, punctuation, paragraph breaks, dialogue structure, speaker names, spaces, and numbers.
11. Leave words written only in hiragana or katakana unchanged unless they are an inseparable part of a kanji-containing word.
12. For names and place names, choose the most contextually probable reading and do not omit the annotation.
13. Put punctuation outside the annotation.
14. Do not insert spaces unless they already exist in the original.
15. Do not use Markdown tables, bullet points, code blocks, explanations, notes, headings, introductions, or summaries in the output.
16. Output only the converted Japanese text.
17. Before answering, verify that every annotated unit follows exactly: [Japanese surface text|hiragana reading|short contextual meaning in English]

Japanese text:
`;await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1800)};
  const evaluate=useCallback((score:number)=>{const e=due[reviewIndex];if(!e)return;const days=[1,2,7,14][score-1];setEntries({...entries,[e.key]:{...e,status:score===1?"review":score===4&&e.streak>=3?"stable":"known",checks:e.checks+1,forgot:e.forgot+(score===1?1:0),streak:score===1?0:e.streak+1,lastChecked:today(),nextReview:addDays(days)}});setShowAnswer(false);setReviewIndex(Math.min(reviewIndex+1,due.length-1));toast(tr(lang,"次回の復習日を更新しました"))},[due,reviewIndex,entries,lang]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(tab!=="review")return;if(e.code==="Space"){e.preventDefault();setShowAnswer(true)}if(showAnswer&&/[1-4]/.test(e.key))evaluate(Number(e.key))};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[tab,showAnswer,evaluate]);
  const readingText=<div className={`reading-text ${vertical?"vertical":""}`} style={{fontSize,lineHeight}}>{parsed.map((p,i)=>p.reading||p.source==="candidate"?<button key={i} className={`word ${entries[p.text]?.status||"new"} ${temp.includes(p.text)?"temporary":""} ${p.source==="candidate"?"dictionary-candidate":""} ${p.source==="ambiguous"&&!entries[p.text]?.reading?"reading-ambiguous":""}`} aria-label={`${p.text}: ${tr(lang,p.source==="candidate"||p.source==="ambiguous"?"読み候補を確認":"読みと学習状態を確認")}`} onClick={()=>setSelected(p.text)}>{p.reading&&visible(p.text)?<ruby>{p.text}<rt style={{fontSize:`${Math.max(10,fontSize*.48)}px`}}>{readingFor(p.text)}{p.meaning?` · ${p.meaning}`:""}</rt></ruby>:p.text}</button>:p.text)}</div>;
  const current=selected?entries[selected]:null;
  const selectedKanji=selected?[...selected].map(c=>SCHOOL_KANJI[c]).filter((k):k is KanjiInfo=>!!k):[];
  const selectedWordCandidates=selected?WORD_READING_CANDIDATES[selected]||[]:[];
  const selectedSource=selected?sourceFor(selected):"candidate";
  return <div className={`app ${dark?"dark":""}`}>
    <header><button className="brand" onClick={()=>setTab("home")} aria-label="ホームへ"><span>{lang==="ja"?"読":"R"}</span><b>漢字リーディング</b></button><div className="header-actions"><label className="language-picker" aria-label="Interface language"><span>{lang==="ja"?"文A":"A"}</span><select value={lang} onChange={e=>setLang(e.target.value as Lang)}>{LANGS.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label><span className="streak">今日も一歩ずつ</span><button className="round" onClick={()=>setDark(!dark)} aria-label="テーマ切替">{dark?"☀":"☾"}</button></div></header>
    <aside aria-label="メインナビゲーション">{NAV.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>navigate(n.id)}><i>{lang!=="ja"&&n.id==="notebook"?"Aa":n.icon}</i><span>{n.label}</span>{n.id==="review"&&due.length>0?<em>{due.length}</em>:null}</button>)}</aside>
    <main>
      {tab==="home"&&<><section className="welcome"><div><small>おはようございます</small><h1>今日も、ひとつずつ。</h1><p>読むほどに、ふりがなが静かに減っていきます。</p></div><button className="primary" onClick={()=>navigate("input")}>文章を読む <span>→</span></button></section><section className="stats"><article><span>今日の復習</span><strong>{due.length}<small>語</small></strong><button onClick={()=>navigate("review")}>復習を始める →</button></article><article><span>覚えた語</span><strong>{known}<small>語</small></strong><p>あなたの読める言葉</p></article><article><span>学習中</span><strong>{Object.keys(entries).length-known}<small>語</small></strong><p>焦らず育てましょう</p></article></section><section className="home-grid"><article className="recent"><div className="section-title"><h2>最近読んだ文章</h2><button onClick={()=>navigate("library")}>すべて見る</button></div>{books.length?books.slice(0,3).map(b=><button className="book-row" key={b.id} onClick={()=>openBook(b)} disabled={!b.body}><span>{tr(lang,"文")}</span><div><b>{b.title}</b><small>{b.body?`${b.lastRead} ${tr(lang,"に読書")}`:tr(lang,"本文削除済み")}</small></div><i>{b.body?"→":"—"}</i></button>):<div className="empty"><span>◫</span><p>{tr(lang,"保存した文章がここに並びます")}</p><button onClick={()=>navigate("input")}>{tr(lang,"最初の文章を読む")}</button></div>}</article><article className="guide"><span>はじめての方へ</span><h2>3ステップで始められます</h2><ol><li><b>1</b><p><strong>文章を貼り付ける</strong><small>読みたい日本語を入力します</small></p></li><li><b>2</b><p><strong>ふりがなで読む</strong><small>分からない語も止まらず読めます</small></p></li><li><b>3</b><p><strong>覚えたらタップ</strong><small>次からふりがなが消えます</small></p></li></ol></article></section></>}
      {tab==="input"&&<section className="panel input-panel"><div className="eyebrow">注釈付き文章入力</div><h1>今日は何を読みますか？</h1><div className="copyright-note">自分で利用できる文章だけを入力してください。著作権に関する法律は国によって異なります。</div><div className="offline-analysis"><div><b>普通の日本語を貼るだけで、AIなしでもふりがなを付けます</b><p>個人辞書と内蔵熟語を優先し、登録のない漢字にも内蔵漢字辞書から推定した読みを表示します。推定部分は点線で区別できます。</p></div><small>文章を外部へ送信しません。推定が違う場合は語を押して修正してください。その端末の個人辞書に保存され、次回から自動的に使われます。</small></div><div className="format-guide"><b>意味と、文脈に合うより正確な読みも必要な場合はAI形式を使えます</b><code>[勉強|べんきょう|studied]しました</code><p>日本語の語・ひらがなの読み・英語の意味を、すべて角括弧の中に入れます。通常の日本語文章も、そのまま利用できます。</p><button onClick={copyPrompt}>{copied?"✓ コピーしました":"新形式のAI用英語プロンプトをコピー"}</button></div><label>タイトル<input value={title} onChange={e=>{setTitle(e.target.value);setDraftSaved(false);setTextUpdatedAt(today())}} /></label><label>日本語の文章<textarea value={text} onChange={e=>{setText(e.target.value);setDraftSaved(false);setTextUpdatedAt(today())}} rows={12}/></label><div className="parse-count">辞書・登録済みの読み：<b>{parsed.filter(p=>p.reading&&p.source!=="candidate").length}</b>　自動推定：<b>{parsed.filter(p=>p.reading&&p.source==="candidate").length}</b></div><div className="actions"><button className="ghost" onClick={()=>{setText(SAMPLE);setDraftSaved(false);setTextUpdatedAt(today())}}>サンプルを読み込む</button><button className="ghost" onClick={()=>{setText("");setTitle("");setDraftSaved(false);setTextUpdatedAt(today())}}>入力を削除</button><button className="secondary" onClick={saveBook}>ライブラリに保存</button><button className="primary" onClick={startReading}>読書画面を開く →</button></div></section>}
      {tab==="reading"&&<section className="reader"><div className="reader-top"><div><div className="eyebrow">リーディング</div><h1>{title}</h1></div><div className="reader-tools"><label>ふりがな<select value={mode} onChange={e=>setMode(e.target.value)}><option value="unknown">未学習だけ</option><option value="all">すべて表示</option><option value="review">復習だけ</option><option value="click">クリックだけ</option><option value="none">すべて非表示</option></select></label><button onClick={()=>setFontSize(Math.max(18,fontSize-2))}>A−</button><button onClick={()=>setFontSize(Math.min(42,fontSize+2))}>A＋</button><button onClick={()=>setVertical(!vertical)}>縦/横</button></div></div><div className="paper">{readingText}</div><div className="reading-legend"><span><i className="legend-dot"/>辞書・登録済みの読み</span><span><i className="legend-ambiguous"/>複数候補の印</span><span><i className="legend-unknown"/>点線はAIを使わない推定読み</span></div><div className="reader-foot"><button onClick={()=>setTab("input")}>← 文章を編集</button><span>語をタップすると、読み方と学習状態を変更できます</span><div><button onClick={()=>navigate("home")}>読書を終了</button><button onClick={saveBook}>保存する</button></div></div></section>}
      {tab==="notebook"&&<Notebook entries={entries} onSelect={setSelected} lang={lang}/>}
      {tab==="review"&&<section className="panel review"><div className="eyebrow">復習モード</div><h1>今日の復習</h1>{due.length?<><p>{reviewIndex+1} / {due.length}</p><div className="review-card"><strong>{due[reviewIndex]?.key}</strong>{showAnswer&&<span>{due[reviewIndex]?.reading}</span>}</div>{!showAnswer?<button className="primary" onClick={()=>setShowAnswer(true)}>読み方を見る <kbd>Space</kbd></button>:<div className="ratings">{["分からなかった","少し迷った","分かった","すぐ分かった"].map((x,i)=><button key={x} onClick={()=>evaluate(i+1)}>{x}<kbd>{i+1}</kbd></button>)}</div>}</>:<div className="empty"><span>✓</span><h2>今日の復習は完了です</h2><p>新しい文章を読んで、言葉を育てましょう。</p></div>}</section>}
      {tab==="library"&&<section className="panel"><div className="section-title"><div><div className="eyebrow">読書ライブラリ</div><h1>保存した文章</h1></div><button className="primary" onClick={()=>navigate("input")}>＋ 新しい文章</button></div><div className="retention-summary">{retention==="never"?tr(lang,"本文を自動削除しない設定です。学習記録は残ります。"):tr(lang,"本文は最後に読んだ日から")+` ${retention} `+tr(lang,"日後に自動削除されます。学習記録は残ります。")}</div><div className="book-grid">{books.map(b=><article key={b.id} className={!b.body?"body-deleted":""}><span>{b.body?tr(lang,"日本語"):tr(lang,"本文削除済み")}</span><h3>{b.title}</h3><p>{b.body?`${b.body.slice(0,75)}…`:tr(lang,"本文は保存期限または手動操作により削除されました。")}</p><small>{b.createdAt} {tr(lang,"登録")}</small><div>{b.body&&<button onClick={()=>openBook(b)}>もう一度読む</button>}<button onClick={()=>setBooks(books.filter(x=>x.id!==b.id))}>削除</button></div></article>)}</div>{!books.length&&<div className="empty"><span>▣</span><p>まだ文章が保存されていません</p></div>}</section>}
      {tab==="history"&&<History entries={entries} lang={lang}/>}
      {tab==="settings"&&<section className="panel settings"><div className="eyebrow">設定</div><h1>読みやすさとデータ</h1><div className="dictionary-summary"><b>{tr(lang,"内蔵漢字辞書：")}{Object.keys(SCHOOL_KANJI).length.toLocaleString()} {tr(lang,"字")}</b><p>{tr(lang,"内蔵一般語辞書：")}{commonWordsData.wordCount.toLocaleString()} {tr(lang,"語")}</p><p>義務教育で扱う常用漢字の音読み・訓読みを収録しています。登録のない漢字にもAIなしで推定読みを表示します。点線の語は、熟語や文脈によって読みが異なる可能性があります。修正した語は個人辞書として保存され、次回から最優先で使われます。</p><p>{tr(lang,"個人辞書：")}{Object.values(entries).filter(e=>e.reading).length.toLocaleString()} {tr(lang,"語")}</p></div><div className="setting-row"><div><b>本文の文字サイズ</b><small>{fontSize}px</small></div><input type="range" min="18" max="42" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></div><div className="setting-row"><div><b>行間</b><small>{lineHeight.toFixed(1)}</small></div><input type="range" min="1.7" max="3" step=".1" value={lineHeight} onChange={e=>setLineHeight(+e.target.value)}/></div><div className="setting-row"><div><b>ダークテーマ</b><small>目の負担を抑えます</small></div><button className="toggle" aria-pressed={dark} onClick={()=>setDark(!dark)}><i/></button></div><section className="privacy-settings"><h2>本文の保存と著作権</h2><p>標準では、最後に読んでから30日後に本文だけを削除します。学習した語・読み・復習記録は残ります。</p><label>本文の保存期間<select value={retention} onChange={e=>updateRetention(e.target.value as Retention)}><option value="7">7日</option><option value="30">30日（標準）</option><option value="90">90日</option><option value="never">削除しない</option></select></label>{retention==="never"&&<div className="copyright-warning">著作権の問題はそれぞれの国によって異なります。保存する文章については、ご自身で責任を持って管理してください。</div>}<label className="check-setting"><input type="checkbox" checked={discardUnsaved} onChange={e=>setDiscardUnsaved(e.target.checked)}/><span><b>保存していない文章は読書終了時に破棄する</b><small>漢字帳と復習記録は残ります。</small></span></label><button className="delete-bodies" onClick={deleteAllBodies}>今すぐ本文を削除</button></section><DataTools entries={entries} books={books} setEntries={setEntries} setBooks={setBooks} toast={toast} lang={lang}/></section>}
      {tab==="settings"&&<SourceNotice lang={lang}/>}
    </main>
    {selected&&<div className="modal-back" onMouseDown={()=>setSelected(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="word-dialog-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label={tr(lang,"閉じる")}>×</button><small>{tr(lang,current?.status==="known"?"覚えた語":current?.status==="review"?"復習が必要":"学習する語")}</small><h2 id="word-dialog-title">{selected}</h2><div className="reading-answer">{readingFor(selected)||tr(lang,"読みはまだ確定していません")}</div><div className={`reading-source ${selectedSource}`}>{sourceLabel(selectedSource)}{selectedSource==="candidate"&&selectedKanji[0]?` · ${readingCandidates(selectedKanji[0]).length}${tr(lang,"候補")}`:""}</div>{(current?.meaning||annotations[selected]?.meaning)&&<div className="meaning-answer">{current?.meaning||annotations[selected]?.meaning}</div>}{selectedWordCandidates.length>1&&!current?.reading&&<div className="word-reading-choices"><b>{tr(lang,"熟語辞書の読み候補")}</b><div>{selectedWordCandidates.map(reading=><button key={reading} className={reading===readingFor(selected)?"current":""} onClick={()=>chooseReading(selected,reading)}>{reading}</button>)}</div><small>{tr(lang,"この語には複数の読みがあります。文に合う読みを選んでください。")}</small></div>}{selectedKanji.length>0&&<div className="kanji-details"><b>{tr(lang,selectedSource==="candidate"?"候補から選ぶ":"内蔵漢字辞書の別候補")}</b>{selectedKanji.map(k=><div className="kanji-row" key={k.literal}><span className="kanji-literal">{k.literal}</span><div className="kanji-readings"><p><small>{tr(lang,"音読み")}</small>{k.onyomi.length?k.onyomi.map(r=>selected.length===1?<button key={r} onClick={()=>chooseReading(selected,r)}>{r}</button>:<span key={r}>{r}</span>):"—"}</p><p><small>{tr(lang,"訓読み")}</small>{k.kunyomi.length?k.kunyomi.map(r=>selected.length===1?<button key={r} onClick={()=>chooseReading(selected,r)}>{r}</button>:<span key={r}>{r}</span>):"—"}</p></div></div>)}<small>{tr(lang,"ここにある読みは候補です。熟語・送り仮名・文脈に合うものがない場合は、下の「読み方を修正」から正しい読みを入力してください。")}</small></div>}<button className="edit-reading" onClick={()=>changeReading(selected)}>✎ {tr(lang,"読み方を修正")}</button><div className="modal-actions"><button className="primary" onClick={()=>upsert(selected,"known")}>{tr(lang,"✓ 覚えた")}</button><button onClick={()=>upsert(selected,"review")}>{tr(lang,"↻ 復習対象に戻す")}</button><button disabled={!readingFor(selected)} onClick={()=>{setTemp([...temp,selected]);setSelected(null);setTimeout(()=>setTemp(v=>v.filter(x=>x!==selected)),5000)}}>{tr(lang,"一度だけ読みを表示")}</button><button disabled={!readingFor(selected)} onClick={()=>{setSession([...session,selected]);setSelected(null)}}>{tr(lang,"この文章では表示")}</button></div><p>{tr(lang,readingFor(selected)?"一度だけ表示した読みは、5秒後に再び隠れます。":"読みを確定すると、個人辞書として次回の文章でも使われます。")}</p></div></div>}
    {notice&&<div className="toast" role="status">✓ {notice}</div>}
  </div>
}

function DictionaryLookup({onSelect,lang}:{onSelect:(x:string)=>void;lang:Lang}){const [query,setQuery]=useState("");const normalized=kataToHira(query.trim());const matches=normalized?Object.values(SCHOOL_KANJI).filter(k=>k.literal.includes(query)||[...k.onyomi,...k.kunyomi].some(r=>cleanReading(r).includes(normalized))).slice(0,24):[];return <section className="dictionary-lookup"><div><b>{tr(lang,"内蔵漢字辞書")}</b><small> {tr(lang,"義務教育の常用漢字")} {Object.keys(SCHOOL_KANJI).length.toLocaleString()}</small></div><input aria-label={tr(lang,"内蔵漢字辞書を検索")} placeholder={tr(lang,"漢字・音読み・訓読みで検索")} value={query} onChange={e=>setQuery(e.target.value)}/>{normalized&&<div className="dictionary-results">{matches.map(k=><button key={k.literal} onClick={()=>onSelect(k.literal)}><b>{k.literal}</b><span>{tr(lang,"音")} {k.onyomi.join("・")||"—"}</span><span>{tr(lang,"訓")} {k.kunyomi.join("・")||"—"}</span></button>)}{!matches.length&&<p>{tr(lang,"一致する漢字がありません")}</p>}</div>}</section>}
function Notebook({entries,onSelect,lang}:{entries:Record<string,Entry>;onSelect:(x:string)=>void;lang:Lang}){const [q,setQ]=useState("");const [filter,setFilter]=useState("all");const list=Object.values(entries).filter(e=>(filter==="all"||e.status===filter)&&(e.key.includes(q)||e.reading.includes(q))).sort((a,b)=>b.learnedAt.localeCompare(a.learnedAt));return <section className="panel"><div className="eyebrow">{tr(lang,"漢字帳")}</div><h1>{tr(lang,"育てている言葉")}</h1><DictionaryLookup onSelect={onSelect} lang={lang}/><div className="filters"><input placeholder={tr(lang,"登録済みの漢字・読み方で検索")} value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{tr(lang,"すべての状態")}</option><option value="learning">{tr(lang,"学習中")}</option><option value="known">{tr(lang,"覚えた")}</option><option value="review">{tr(lang,"復習が必要")}</option><option value="stable">{tr(lang,"安定")}</option></select></div><div className="table"><div className="tr th"><span>{tr(lang,"語・読み")}</span><span>{tr(lang,"状態")}</span><span>{tr(lang,"次回復習")}</span><span>{tr(lang,"確認 / 忘れ")}</span></div>{list.map(e=><button className="tr" key={e.key} onClick={()=>onSelect(e.key)}><span><b>{e.key}</b><small>{e.reading}</small></span><span><i className={`badge ${e.status}`}>{tr(lang,({learning:"学習中",known:"覚えた",review:"復習が必要",stable:"安定"} as Record<string,string>)[e.status])}</i></span><span>{e.nextReview}</span><span>{e.checks} / {e.forgot}</span></button>)}</div>{!list.length&&<div className="empty"><span>字</span><p>{tr(lang,"文章中の語をタップすると、ここに追加されます")}</p></div>}</section>}
function History({entries,lang}:{entries:Record<string,Entry>;lang:Lang}){const all=Object.values(entries);const max=Math.max(1,...all.map(e=>e.checks));return <section className="panel"><div className="eyebrow">{tr(lang,"学習履歴")}</div><h1>{tr(lang,"積み重ねが見える場所")}</h1><div className="stats compact"><article><span>{tr(lang,"登録した語")}</span><strong>{all.length}<small>{tr(lang,"語")}</small></strong></article><article><span>{tr(lang,"確認した回数")}</span><strong>{all.reduce((a,e)=>a+e.checks,0)}<small>{tr(lang,"回")}</small></strong></article><article><span>{tr(lang,"よく忘れる語")}</span><strong>{all.filter(e=>e.forgot>=2).length}<small>{tr(lang,"語")}</small></strong></article></div><h2 className="chart-title">{tr(lang,"言葉ごとの確認回数")}</h2><div className="chart">{all.slice(0,12).map(e=><div key={e.key}><span>{e.key}</span><i style={{width:`${Math.max(7,e.checks/max*100)}%`}}/><b>{e.checks}</b></div>)}</div>{!all.length&&<div className="empty"><p>{tr(lang,"学習を始めるとグラフが表示されます")}</p></div>}</section>}
function DataTools({entries,books,setEntries,setBooks,toast,lang}:{entries:Record<string,Entry>;books:Book[];setEntries:(x:Record<string,Entry>)=>void;setBooks:(x:Book[])=>void;toast:(x:string)=>void;lang:Lang}){const exp=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,entries,books},null,2)],{type:"application/json"}));a.download=`kanji-reading-${today()}.json`;a.click()};const imp=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));setEntries(d.entries||{});setBooks(d.books||[]);toast(tr(lang,"データを復元しました"))}catch{alert(tr(lang,"JSONファイルを読み込めませんでした"))}};r.readAsText(f)};return <div className="data-tools"><h2>{tr(lang,"データ管理")}</h2><div><button onClick={exp}>{tr(lang,"JSONを書き出す")}</button><label className="file-btn">{tr(lang,"JSONを読み込む")}<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&imp(e.target.files[0])}/></label></div><div className="danger"><button onClick={()=>confirm(tr(lang,"漢字帳を初期化しますか？"))&&setEntries({})}>{tr(lang,"漢字帳を初期化")}</button><button onClick={()=>confirm(tr(lang,"読書履歴を初期化しますか？"))&&setBooks([])}>{tr(lang,"読書履歴を初期化")}</button></div></div>}
